export const recipes = [
  { id: 1, name: "avocado_lime", image: "../images/avocado_lime.jpg" },
  { id: 2, name: "bagels", image: "../images/bagels.jpg" },
  {
    id: 3,
    name: "beef_bone_in_chuck_roast",
    image: "../images/beef_bone_in_chuck_roast.jpg",
  },
  {
    id: 4,
    name: "beef_sirloin_tip_roast",
    image: "../images/beef_sirloin_tip_roast.jpg",
  },
  { id: 5, name: "bone_broth", image: "../images/bone_broth.jpg" },
  { id: 6, name: "boneless_ribs", image: "../images/boneless_ribs.jpg" },
  { id: 7, name: "bread_loaf", image: "../images/bread_loaf.jpg" },
  {
    id: 8,
    name: "buttermilk_pancakes",
    image: "../images/buttermilk_pancakes.jpg",
  },
  {
    id: 9,
    name: "cabbage_and_meatball",
    image: "../images/cabbage_and_meatball.jpg",
  },
  { id: 10, name: "carrot_cake", image: "../images/carrot_cake.jpg" },
  {
    id: 11,
    name: "cauliflower_shrimp",
    image: "../images/cauliflower_shrimp.jpg",
  },
  { id: 12, name: "cheese_burgers", image: "../images/cheese_burgers.jpg" },
  { id: 13, name: "cherry_pie", image: "../images/cherry_pie.jpg" },
  {
    id: 14,
    name: "chicken_garlic_aioli_tacos",
    image: "../images/chicken_garlic_aioli_tacos.jpg",
  },
  {
    id: 15,
    name: "chicken_nugs_and_french_fries",
    image: "../images/chicken_nugs_and_french_fries.jpg",
  },
  { id: 16, name: "chicken_pot_pie", image: "../images/chicken_pot_pie.jpg" },
  { id: 17, name: "chipotle", image: "../images/chipotle.jpg" },
  { id: 18, name: "chocolate_candy", image: "../images/chocolate_candy.jpg" },
  {
    id: 19,
    name: "chocolate_cookies",
    image: "../images/chocolate_cookies.jpg",
  },
  {
    id: 20,
    name: "chocplate_rice_krispies",
    image: "../images/chocplate_rice_krispies.jpg",
  },
  {
    id: 21,
    name: "chulettas_and_platanos",
    image: "../images/chulettas_and_platanos.jpg",
  },
  { id: 22, name: "dippy_eggs", image: "../images/dippy_eggs.jpg" },
  {
    id: 23,
    name: "dutch_oven_beff_stew",
    image: "../images/dutch_oven_beff_stew.jpg",
  },
  { id: 24, name: "english_muffins", image: "../images/english_muffins.jpg" },
  {
    id: 25,
    name: "fathers_day_special",
    image: "../images/fathers_day_special.jpg",
  },
  { id: 26, name: "flour_tortilla", image: "../images/flour_tortilla.jpg" },
  { id: 27, name: "french_toast", image: "../images/french_toast.jpg" },
  { id: 28, name: "grape_jelly", image: "../images/grape_jelly.jpg" },
  { id: 29, name: "kabobs", image: "../images/kabobs.jpg" },
  {
    id: 30,
    name: "lemon_chicken_mushroom",
    image: "../images/lemon_chicken_mushroom.jpg",
  },
  { id: 31, name: "lotion", image: "../images/lotion.jpg" },
  {
    id: 32,
    name: "mac_and_cheese_cicd",
    image: "../images/mac_and_cheese_cicd.jpg",
  },
  {
    id: 33,
    name: "mac_and_cheese_og",
    image: "../images/mac_and_cheese_og.jpg",
  },
  { id: 34, name: "mofongp", image: "../images/mofongp.jpg" },
  { id: 35, name: "paella", image: "../images/paella.jpg" },
  { id: 36, name: "peach_jelly", image: "../images/peach_jelly.jpg" },
  {
    id: 37,
    name: "peanut_butter_oats",
    image: "../images/peanut_butter_oats.jpg",
  },
  { id: 38, name: "pernil", image: "../images/pernil.jpg" },
  { id: 39, name: "pie_crust", image: "../images/pie_crust.jpg" },
  { id: 40, name: "pizza_crust", image: "../images/pizza_crust.jpg" },
  { id: 41, name: "platanos_garlic", image: "../images/platanos_garlic.jpg" },
  { id: 41, name: "pollo_guisado", image: "../images/pollo_guisado.jpg" },
  {
    id: 42,
    name: "rostiaire_chicken",
    image: "../images/rostiaire_chicken.jpg",
  },
  { id: 43, name: "salmon", image: "../images/salmon.jpg" },
  { id: 44, name: "sausage_subs", image: "../images/sausage_subs.jpg" },
  { id: 45, name: "shawns_chili", image: "../images/shawns_chili.jpg" },
  { id: 46, name: "shawns_lemonade", image: "../images/shawns_lemonade.jpg" },
  { id: 47, name: "shawns_tea", image: "../images/shawns_tea.jpg" },
  { id: 48, name: "shepherds_pie", image: "../images/shepherds_pie.jpg" },
  { id: 49, name: "shoulder_roast", image: "../images/shoulder_roast.jpg" },
  {
    id: 50,
    name: "spaghetti_and_meatballs",
    image: "../images/spaghetti_and_meatballs.jpg",
  },
  { id: 51, name: "spaghetti", image: "../images/spaghetti.jpg" },
  { id: 52, name: "spanish_rice", image: "../images/spanish_rice.jpg" },
  { id: 53, name: "steak_poatato", image: "../images/steak_poatato.jpg" },
  { id: 54, name: "stir_fry", image: "../images/stir_fry.jpg" },
  { id: 55, name: "stove_cleaner", image: "../images/stove_cleaner.jpg" },
  { id: 56, name: "strawberry_jam", image: "../images/strawberry_jam.jpg" },
  { id: 57, name: "stuffed_cabbage", image: "../images/stuffed_cabbage.jpg" },
  { id: 58, name: "stuffed_chicken", image: "../images/stuffed_chicken.jpg" },
  { id: 59, name: "sushi", image: "../images/sushi.jpg" },
  {
    id: 60,
    name: "swett_potato_casserole",
    image: "../images/swett_potato_casserole.jpg",
  },
  {
    id: 61,
    name: "thanksgiving_utensils",
    image: "../images/thanksgiving_utensils.jpg",
  },
  { id: 62, name: "tomato_sauce", image: "../images/tomato_sauce.jpg" },
  { id: 63, name: "top_round", image: "../images/top_round.jpg" },
  { id: 64, name: "tortilla_chips", image: "../images/tortilla_chips.jpg" },
  { id: 65, name: "waffles_pancakes", image: "../images/waffles_pancakes.jpg" },
  { id: 66, name: "zuchini_bread", image: "../images/zuchini_bread.jpg" },
]
