export const recipes = [
  {
    id: 1,
    name: "avocado_lime",
    image: "../images/avocado_lime.jpg",
    type: ["Sauce"],
  },
  { id: 2, name: "bagels", 
    image: "../images/bagels.jpg", 
    type: ["Bakery"] },
  {
    id: 3,
    name: "beef_bone_in_chuck_roast",
    image: "../images/beef_bone_in_chuck_roast.jpg",
    type: ["Main"],
  },
  {
    id: 4,
    name: "beef_sirloin_tip_roast",
    image: "../images/beef_sirloin_tip_roast.jpg",
    type: ["Main"],
  },
  {
    id: 5,
    name: "bone_broth",
    image: "../images/bone_broth.jpg",
    type: ["Sauce"],
  },
  {
    id: 6,
    name: "boneless_ribs",
    image: "../images/boneless_ribs.jpg",
    type: ["Main", "Sauce"],
  },
  {
    id: 7,
    name: "bread_loaf",
    image: "../images/bread_loaf.jpg",
    type: ["Bakery"],
  },
  {
    id: 8,
    name: "buttermilk_pancakes",
    image: "src/images/buttermilk_pancakes.jpg",
    type: ["Breakfast"],
  },
  {
    id: 9,
    name: "cabbage_and_meatball",
    image: "../images/cabbage_and_meatball.jpg",
    type: ["Main"],
  },
  {
    id: 10,
    name: "carrot_cake",
    image: "../images/carrot_cake.jpg",
    type: ["Dessert"],
  },
  {
    id: 11,
    name: "cauliflower_shrimp",
    image: "../images/cauliflower_shrimp.jpg",
    type: ["Main"],
  },
  {
    id: 12,
    name: "cheese_burgers",
    image: "../images/cheese_burgers.jpg",
    type: ["Main"],
  },
  {
    id: 13,
    name: "cherry_pie",
    image: "../images/cherry_pie.jpg",
    type: ["Dessert", "Holiday_Thanksgiving"],
  },
  {
    id: 14,
    name: "chicken_garlic_aioli_tacos",
    image: "../images/chicken_garlic_aioli_tacos.jpg",
    type: ["Main", "Sauce"],
  },
  {
    id: 15,
    name: "chicken_nugs_and_french_fries",
    image: "../images/chicken_nugs_and_french_fries.jpg",
    type: ["Side", "Main"],
  },
  {
    id: 16,
    name: "chicken_pot_pie",
    image: "../images/chicken_pot_pie.jpg",
    type: ["Main"],
  },
  {
    id: 17,
    name: "chipotle",
    image: "../images/chipotle.jpg",
    type: ["Main", "Sauce"],
  },
  {
    id: 18,
    name: "chocolate_candy",
    image: "../images/chocolate_candy.jpg",
    type: ["Dessert"],
  },
  {
    id: 19,
    name: "chocolate_cookies",
    image: "../images/chocolate_cookies.jpg",
    type: ["Dessert"],
  },
  {
    id: 20,
    name: "chocplate_rice_krispies",
    image: "../images/chocplate_rice_krispies.jpg",
    type: ["Dessert"],
  },
  {
    id: 21,
    name: "chulettas_and_platanos",
    image: "../images/chulettas_and_platanos.jpg",
    type: ["Side", "Main"],
  },
  {
    id: 22,
    name: "dippy_eggs",
    image: "../images/dippy_eggs.jpg",
    type: ["Breakfast"],
  },
  {
    id: 23,
    name: "dutch_oven_beff_stew",
    image: "../images/dutch_oven_beff_stew.jpg",
    type: ["Main"],
  },
  {
    id: 24,
    name: "english_muffins",
    image: "../images/english_muffins.jpg",
    type: ["Bakery"],
  },
  {
    id: 25,
    name: "fathers_day_special",
    image: "../images/fathers_day_special.jpg",
    type: ["Main"],
  },
  {
    id: 26,
    name: "flour_tortilla",
    image: "../images/flour_tortilla.jpg",
    type: ["Side", "Pre-requisite"],
  },
  {
    id: 27,
    name: "french_toast",
    image: "../images/french_toast.jpg",
    type: ["Breakfast"],
  },
  {
    id: 28,
    name: "grape_jelly",
    image: "../images/grape_jelly.jpg",
    type: ["Jelly"],
  },
  { id: 29, 
    name: "kabobs", 
    image: "../images/kabobs.jpg", 
    type: ["Main"] },
  {
    id: 30,
    name: "lemon_chicken_mushroom",
    image: "../images/lemon_chicken_mushroom.jpg",
    type: ["Main"],
  },
  { id: 31, 
    name: "lotion", 
    image: "../images/lotion.jpg", 
    type: ["Misc"] },
  {
    id: 32,
    name: "mac_and_cheese_cicd",
    image: "../images/mac_and_cheese_cicd.jpg",
    type: ["Main", "Holiday_Thanksgiving"],
  },
  {
    id: 33,
    name: "mac_and_cheese_og",
    image: "../images/mac_and_cheese_og.jpg",
    type: ["Main", "Holiday_Thanksgiving"],
  },
  {
    id: 34,
    name: "mofongo",
    image: "../images/mofongo.jpg",
    type: ["Side", "Main", "Pre-requisite"],
  },
  { id: 35, 
    name: "paella", 
    image: "../images/paella.jpg", 
    type: ["Main"] },
  {
    id: 36,
    name: "peach_jelly",
    image: "../images/peach_jelly.jpg",
    type: ["Jelly"],
  },
  {
    id: 37,
    name: "peanut_butter_oats",
    image: "../images/peanut_butter_oats.jpg",
    type: ["Dessert"],
  },
  {
    id: 38,
    name: "pernil",
    image: "../images/pernil.jpg",
    type: ["Main", "Holiday_Christmas"],
  },
  {
    id: 39,
    name: "pie_crust",
    image: "../images/pie_crust.jpg",
    type: ["Bakery"],
  },
  {
    id: 40,
    name: "pizza_crust",
    image: "../images/pizza_crust.jpg",
    type: ["Bakery"],
  },
  {
    id: 41,
    name: "platanos_garlic",
    image: "../images/platanos_garlic.jpg",
    type: ["Main", "Sauce"],
  },
  {
    id: 41,
    name: "pollo_guisado",
    image: "../images/pollo_guisado.jpg",
    type: ["Main"],
  },
  {
    id: 42,
    name: "rostiaire_chicken",
    image: "../images/rostiaire_chicken.jpg",
    type: ["Main"],
  },
  { id: 43, 
    name: "salmon", 
    image: "../images/salmon.jpg", 
    type: ["Main"] },
  {
    id: 44,
    name: "sausage_subs",
    image: "../images/sausage_subs.jpg",
    type: ["Main"],
  },
  {
    id: 45,
    name: "shawns_chili",
    image: "../images/shawns_chili.jpg",
    type: ["Main"],
  },
  {
    id: 46,
    name: "shawns_lemonade",
    image: "../images/shawns_lemonade.jpg",
    type: ["Drink"],
  },
  {
    id: 47,
    name: "shawns_tea",
    image: "../images/shawns_tea.jpg",
    type: ["Drink"],
  },
  {
    id: 48,
    name: "shepherds_pie",
    image: "../images/shepherds_pie.jpg",
    type: ["Main"],
  },
  {
    id: 49,
    name: "shoulder_roast",
    image: "../images/shoulder_roast.jpg",
    type: ["Main"],
  },
  {
    id: 50,
    name: "spaghetti_and_meatballs",
    image: "../images/spaghetti_and_meatballs.jpg",
    type: ["Main", "Pre-requisite"],
  },
  { id: 51, 
    name: "spaghetti", 
    image: "../images/spaghetti.jpg", 
    type: ["Pre-requisite"] },
  {
    id: 52,
    name: "spanish_rice",
    image: "../images/spanish_rice.jpg",
    type: ["Side"],
  },
  {
    id: 53,
    name: "steak_poatato",
    image: "../images/steak_poatato.jpg",
    type: ["Main"],
  },
  {
    id: 54,
    name: "stir_fry",
    image: "../images/stir_fry.jpg",
    type: ["Pre-requisite"],
  },
  {
    id: 55,
    name: "stove_cleaner",
    image: "../images/stove_cleaner.jpg",
    type: ["Misc"],
  },
  {
    id: 56,
    name: "strawberry_jam",
    image: "../images/strawberry_jam.jpg",
    type: ["Jelly"],
  },
  {
    id: 57,
    name: "stuffed_cabbage",
    image: "../images/stuffed_cabbage.jpg",
    type: ["Main"],
  },
  {
    id: 58,
    name: "stuffed_chicken",
    image: "../images/stuffed_chicken.jpg",
    type: ["Main"],
  },
  { id: 59, 
    name: "sushi", 
    image: "../images/sushi.jpg", 
    type: ["Main"] },
  {
    id: 60,
    name: "sweet_potato_casserole",
    image: "../images/sweet_potato_casserole.jpg",
    type: ["Holiday_Thanksgiving"],
  },
  {
    id: 61,
    name: "thanksgiving_utensils",
    image: "../images/thanksgiving_utensils.jpg",
    type: ["Holiday_Thanksgiving"],
  },
  {
    id: 62,
    name: "tomato_sauce",
    image: "../images/tomato_sauce.jpg",
    type: ["Sauce"],
  },
  {
    id: 63,
    name: "top_round",
    image: "../images/top_round.jpg",
    type: ["Main"],
  },
  {
    id: 64,
    name: "tortilla_chips",
    image: "../images/tortilla_chips.jpg",
    type: ["Side", "Pre-requisite"],
  },
  {
    id: 65,
    name: "waffles_pancakes",
    image: "../images/waffles_pancakes.jpg",
    type: ["Breakfast"],
  },
  {
    id: 66,
    name: "zuchini_bread",
    image: "../images/zuchini_bread.jpg",
    type: ["Dessert"],
  },
  {
    name: "taco_dip",
    image: "Errr...loading...taco_dip",
    type: ["Main"],
  },
]
