export const recipes = [
  {
    name: "Avocado Lime",
    image: "../images/avocado_lime.jpg",
    type: ["Sauce"],
    ingredients: [
      "3 tbsp lime juice",
      "2 avocados",
      "1 c cashews",
      "2 tbsp avocado oil",
      "1 c spinach",
      "1 tsp salt",
    ],
    steps: ["Add all ingredients to blender"],
  },
  {
    name: "Bagel(3)",
    image: "../images/bagels.jpg",
    type: ["Bakery"],
    ingredients: [
      "1/2 c soft white flour",
      "1/2 c hard white flour",
      "227g whole milk greek yogurt",
      "2 tsp baking powder",
      "1 tsp salt",
      "1 egg",
      "everything but the bagel seasoning",
    ],
    steps: [
      "Set oven to 400F",
      "In a bowl mix flour, baking powder, and salt",
      "Add yogurt and mix with fork",
      "Knead with oiled hands for 5 minutes",
      "Rest for 5 minutes",
      "Add oil to hands and create 3 bagel shapes with extra large holes",
      "In a small bowl mix egg and brush onto bagels",
      "Sprinkle Everything But the Bagel Seasoning",
      "Bake for 30 minutes",
    ],
  },
  {
    name: "Beef Bone in Chuck Roast",
    image: "../images/beef_bone_in_chuck_roast.jpg",
    type: ["Main"],
    ingredients: [
      "4 lb chuck roast",
      "3 tbsp olive oil",
      "1 tbsp onion powder",
      "1 tbsp garlic powder",
      "1 tbsp thyme",
      "1 tbsp salt",
      "1 tbsp pepper",
      "1 tsp red chili flakes",
      "1 tsp smoked paprika",
    ],
    steps: [
      "In a small bowl mix onion, garlic, thyme, salt, pepper, chili flakes, and smoked paprika",
      "Add seasoning all over roast and marinade for at least 1 hr in the fridge",
      "Take roast out of fridge 1 hr before cooking",
      "Set oven to 275F",
      "In dutch oven add olive oil and sear all sides of roast",
      "Bake for 10 minutes/lb",
      "* Roast temp: 145F",
    ],
  },
  {
    name: "Beef Sirloin Tip Roast",
    image: "../images/beef_sirloin_tip_roast.jpg",
    type: ["Main"],
    ingredients: [
      "4 lb beef sirloin tip roast",
      "olive oil",
      "salt",
      "pepper",
      "2 lbs frozen beef bones",
      "1 gal of water",
      "2 tbsp salt",
      "1 tbsp onion powder",
      "1 tbsp garlic powder",
      "1 tsp smoked paprika",
    ],
    steps: [
      "Bake bones in oven at 400F for 1 hr",
      "Add bones, bone drippings, 2 tbsp salt, and water to pot",
      "Boil then simmer for 4 hrs",
      "Set oven to 400F",
      "Salt and pepper each side of the roast",
      "In dutch oven heat with olive oil and sear each side of roast",
      "Add broth, onion, garlic, and smoked paprika",
      "Bake for 15 min and set oven to 300F",
      "Bake for 45 minutes per 2 lbs of meat",
      "Shred while still in pot",
    ],
  },
  {
    name: "Bone Broth",
    image: "../images/bone_broth.jpg",
    type: ["Sauce"],
    ingredients: ["2 lbs frozen beef bones", "1 gal of water", "2 tbsp salt"],
    steps: [
      "Bake bones in oven at 400F for 1 hr",
      "Add bones, bone drippings, salt, and water to pot",
      "Boil then simmer for 4 hrs",
    ],
  },
  {
    name: "Boneless Rib",
    image: "../images/boneless_ribs.jpg",
    type: ["Main"],
    ingredients: [
      "1 lb of any meat",
      "Broccoli",
      "2 tbsp honey",
      "1 1/2 tsp chili flakes",
      "1 tsp smoked paprika",
      "1 1/2 tsp salt",
      "2 tbsp olive oil",
    ],
    steps: [
      "Thinly slice meat and put in a bowl",
      "To bowl add honey, chili flakes, smoked paprika, salt, and olive oil",
      "Marinade for 1 hour",
      "Remove meat 30 minutes before cooking",
      "Chop broccoli",
      "Cook meat in pan and add broccoli",
      "Set flame high to burn off extra liquid",
    ],
  },
  {
    name: "Bread Loaf",
    image: "../images/bread_loaf.jpg",
    type: ["Bakery"],
    ingredients: [
      "1 tbsp yeast",
      "1 1/2 c 115F water",
      "3 1/2 c soft white flour",
      "1/2 c hard white flour",
      "1/4 c olive oil",
      "1/4 c honey",
      "2 tsp salt",
    ],
    steps: [
      "Mix yeast and water in a bowl",
      "Stir until yeast is dissolved",
      "Add 1 1/2 c soft white flour and mix",
      "Cover and rest for 20 minutes or until bubbly",
      "Add remaining soft white flour, honey, oil, and salt",
      "Knead in stand mixer until dough ball forms, about 5 minutes",
      "If dough is sticking to sides slowly add hard white flour a small amount at a time",
      "Flour counter and shape dough into a long rectangle",
      "Fold into thirds then roll the long way and pinch the ends under",
      "Place in parchment paper before putting in bread pan",
      "Let rest for 1 hour or until the height of the bread pan",
      "Heat oven to 350F and bake for 40 minutes",
      "Let cool before slicing",
    ],
  },
  {
    name: "Black Beans",
    image: "../images/black_beans.jpg",
    type: ["Side"],
    ingredients: ["2 c water", "1/2 c black beans", "1 tsp salt"],
    steps: ["Add all to pot and bring to boil", "Simmer for 2 hrs"],
  },
  {
    name: "Buffalo Sauce(coats 10 wings)",
    image: "no image found",
    type: ["Sauce"],
    ingredients: ["3 tbsp butter", "1/4 c buffalo sauce"],
    steps: ["Melt down butter in pan", "Add buffalo sauce and stir"],
  },
  {
    name: "Strawberry Lemonade",
    image: "no image found",
    type: ["Drink"],
    ingredients: [
      "1 cup water",
      "2 tbsp agave",
      "3 tbsp lemon juice",
      "4 strawberries",
      "ice",
    ],
    steps: ["Add all to blender and blend", "Fill with ice and blend"],
  },
  {
    name: "Boxed Mac and Cheese",
    image: "no image found",
    type: ["Main"],
    ingredients: ["1 box mac and cheese", "1/4 c milk", "2 tbsp butter"],
    steps: [
      "Set oven to 350F",
      "Follow box instructions",
      "Bake for 30 min",
      "Broil on hi for 5 min",
    ],
  },
  {
    name: "Cabbage and Meatball",
    image: "../images/cabbage_and_meatball.jpg",
    type: ["Main", "Friday_Favorites"],
    ingredients: [
      "1 cabbage",
      "1 lb ground beef",
      "8 red potatoes",
      "8 tomatoes",
      "1 bulb of garlic",
      "2 tbsp salt",
      "1 Gal freezer bag of frozen veggies",
      "2 tbsp salt",
      "3 qts Water",
    ],
    steps: [
      "Fill a giant pot 3/4 of the way(3 gal) with water",
      "Add freezer bag of veggies to pot and boil for 30 min then simmer for 4-5 hours",
      "Strain and add broth back to pot",
      "Chop cabbage into quarters",
      "Chop potatoes in half",
      'Remove top core of tomatoes and mark an "X" on the bottom',
      "Chop hard ends of garlic",
      "Make 1 inch meatballs",
      "Add all to giant pot and simmer for 2 hours",
      "* Save all leftover veggies in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Carrot Cake",
    image: "../images/carrot_cake.jpg",
    type: ["Dessert"],
    ingredients: [
      "3 c shredded carrots",
      "1/2 tsp ginger",
      "2 eggs",
      "1 tsp baking powder",
      "1/2 tsp baking soda",
      "6 tbsp agave",
      "1 tsp cinnamon",
      "1/4 tsp cloves",
      "1/4 tsp nutmeg",
      "1/2 tsp salt",
      "3 tsp vanilla",
      "1/2 c olive oil",
      "1 c hard red flour",
    ],
    steps: ["Mix all together", "Bake at 350F for 50 min"],
  },
  {
    name: "Cauliflower Shrimp",
    image: "../images/cauliflower_shrimp.jpg",
    type: ["Main"],
    ingredients: [
      "1 head of cauliflower",
      "1 lb shrimp",
      "1/2 green pepper",
      "1/2 yellow onion",
      "1 garlic bulb",
      "shelled edamame",
      "2 tsp onion powder",
      "2 tsp garlic powder",
      "1 tsp salt",
      "1 tsp basil",
    ],
    steps: [
      "Chop cauliflower, green pepper, onion, and garlic",
      "Cook pepper and onion until lightly browned",
      "Add all ingredients to pan and cook until shrimp is pink",
      "* Save leftover veggies, minus cauliflower, in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Cheese Burgers",
    image: "../images/cheese_burgers.jpg",
    type: ["Main"],
    ingredients: [
      "1/2 tbsp yeast",
      "3/4 c 115F water",
      "1 3/4 c soft white flour",
      "1/4 c hard white flour",
      "1/8 c olive oil",
      "1/8 c honey",
      "1 tsp salt",
      "1 lb ground beef or patties",
      "cheese",
      "red onion",
      "1 tomato",
      "lettuce",
      "ketchup",
      "mayo",
      "spicy brown mustard",
      "bacon",
    ],
    steps: [
      "Mix yeast and water in a bowl",
      "STir until yeast is dissolved",
      "Add 1 1/2 c soft white flour and mix",
      "Cover and rest for 20 minutes or until bubbly",
      "Add remaining soft white flour, honey, oil, and salt",
      "Knead in stand mixer until dough ball forms, about 5 minutes",
      "If dough is sticking to sides slowly add hard white flour a small amount at a time",
      "Flour counter and shape dough into burger bun shape",
      "Place on parchment paper and let rest for 1 hour",
      "Heat oven to 350F and bake for 20 minutes",
      "Bake bacon in oven 425F for 15 minutes",
      "Form burger patties and cook/grill",
      "Stack it",
      "* burger temp: 185F",
      "* Save all leftover veggies in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Cherry Pie",
    image: "../images/cherry_pie.jpg",
    type: ["Dessert", "Holiday_Thanksgiving"],
    ingredients: [
      "2 c soft white flour",
      "1/4 tsp salt",
      "3 tbsp cold butter",
      "1/4 c + 3 tbsp cold coconut oil",
      "1/4 c ice water",
      "3 cans Oregon red tart cherries",
      "1 tbsp lemon",
      "1/4 tsp almond extract",
      "2/3 c agave",
      "3/4 c brown sugar",
      "2 tbsp cinnamon",
    ],
    steps: [
      "In a the stand mixer bowl whisk flour and salt",
      "Place in fridge for 20 min",
      "Whisk in cubed butter mix for 1 min on lvl 1",
      "Whisk in coconut oil at lvl 4, should look like dry cookie dough",
      "Replace whisk with dough hook and slowly add the ice water until it looks like wet cookie dough",
      "Roll into a ball and place in fridge for 2 hrs",
      "Flour counter, roll out dough, place in pan and leave in fridge for 30 min",
      "In a shallow pan add 1 1/2 cans of cherry juice, all the cherries, lemon, almond extract, and agave",
      "Cook in medium heat until it starts to thicken",
      "Set oven to 425F and bake crust for 15 min",
      "Add filling",
      "Place in oven for 15 min",
      "Lower oven to 350 for 35 min",
      "Mix the sugar and cinnamon and pour over pie",
      "Bake for another 5 min",
    ],
  },
  {
    name: "Chicken Garlic Aioli Tacos",
    image: "../images/chicken_garlic_aioli_tacos.jpg",
    type: ["Main", "Friday_Favorites"],
    ingredients: [
      "2 tsp salt",
      "1 2/3 cup 100F water",
      "2 1/2 c masa harina",
      "2 chicken breast",
      "5 tbsp mayo",
      "1 tbsp basil",
      "2 garlic bulbs",
      "2 tomatoes",
    ],
    steps: [
      "Mix salt, water, masa harina with a fork in a bowl",
      "Knead until smooth",
      "Form 12 1 1/2 inch balls",
      "Rest for at least 30 minutes",
      "Heat electric griddle on high",
      "Chop garlic",
      "Chop tomatoes",
      "Add all to a bowl and mix",
      "Let sit for at least 15 minutes",
      "Cut chicken into strips and cook in pan",
      "Flatten each ball and cook for 2 minutes each side",
      "* Chicken temp: 165F",
      "* Save all leftover veggies in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Chicken Nugs and French Fries",
    image: "../images/chicken_nugs_and_french_fries.jpg",
    type: ["Main"],
    ingredients: [
      "quart olive oil",
      "1 chicken breast",
      "2 brown potatoes",
      "2 c white flour",
      "1/2 tbsp salt",
      "1/2 tbsp onion powder",
      "1/2 tbsp garlic powder",
      "2 egg",
      "1/3 c milk",
    ],
    steps: [
      "In blender add raw chicken breast and 1 uncooked potato",
      "Create nugget shapes and put in freezer for 30 minutes",
      "Heat a dutch oven sized pan and add olive oil halfway up the pan",
      "Chop potato into fry, rinse in water, then pat dry",
      "Mix egg and milk in small bowl",
      "In a bowl mix flour, salt, onion, and garlic",
      "Once pan has reached 350F remove nuggets from freezer",
      "Dip frozen nuggets into milk mixture, flour mixture, milk, and flour again",
      "Once they pop up and are golden brown remove from pan",
      "Once all nuggets are cooked add fry's and fry for 20 minutes",
    ],
  },
  {
    name: "Chicken Pot Pie",
    image: "../images/chicken_pot_pie.jpg",
    type: ["Main", "Friday_Favorites"],
    ingredients: [
      "2 c soft white flour",
      "1/4 tsp salt",
      "3 tbsp cold butter",
      "1/4 c + 3 tbsp cold coconut oil",
      "1/4 c ice water",
      "2 chicken breasts",
      "1 carrot",
      "1 celery",
      "1/2 c peas",
      "2 brown potatoes",
      "1 tbsp thyme",
      "1/2 c yellow onion",
      "2 c chicken broth",
      "4 tbsp flour",
      "1/2 c half and half",
      "pinch of nutmeg",
      "4 tbsp butter",
      "salt",
      "pepper",
    ],
    steps: [
      "In a the stand mixer bowl whisk flour and salt",
      "Place in fridge for 20 min",
      "Whisk in cubed butter mix for 1 min on lvl 1",
      "Whisk in coconut oil at lvl 4, should look like dry cookie dough",
      "Replace whisk with dough hook and slowly add the ice water until it looks like wet cookie dough",
      "Roll into a ball and place in fridge for 2 hrs",
      "Flour counter, roll out dough, place in pan",
      "Prepare 2 dishes for filling and leave in fridge for 30 min",
      "Bake chicken breast in oven at 350F for 25 minutes",
      "Remove chicken and set oven to 400F",
      "Chop chicken into cubes",
      "Add broth, potatoes, carrots, onion, celery, carrot, and peas to pot",
      "Once pot is boiling put it to simmer for 10 minutes",
      "In a separate pan melt butter and mix in flour until golden brown for roux",
      "Add half and half, nutmeg, thyme, salt, pepper to roux until pasty",
      "Add roux to broth",
      "Bake for 45 minutes",
    ],
  },
  {
    name: "Chipotle",
    image: "../images/chipotle.jpg",
    type: ["Main", "Friday_Favorites"],
    ingredients: [
      "1 lb steak",
      "1 c white rice",
      "3 tsp salt",
      "1 tbsp coconut oil",
      "1 1/2 c water",
      "2 c water",
      "1/2 c black beans",
      "1 bunch of cilantro",
      "1 lime",
      "3 avocados",
      "2 tomatoes",
      "1/4 c red onion",
      "1 yellow onion",
      "1 green pepper",
      "1/4 c olive oil",
      "1 corn",
    ],
    steps: [
      "Add water, salt, oil, and rice to pot",
      "Bring to boil then simmer for 25 minutes",
      "Add 2c water, 1/2 c black beans, and 1 tsp salt to pot and bring to boil",
      "Simmer for 2 hrs",
      "Set oven to 450F",
      "Slice avocados and mash in a bowl",
      "Roll lime, slice in half and squeeze juice into bowl",
      "Chop red onion, tomato, and 1/2 bunch of cilantro and add to bowl",
      "Heat cast iron skillet",
      "Once you see smoke from skillet add oil",
      "Add Sliced green peppers and half sliced onions to pan",
      "Once you see char on peppers and onions move to one side of skillet",
      "Add sliced corn kernels",
      "Turn off heat once corn gets a char",
      "Add a good layer of salt all over steak",
      "Cook steak on cast iron skillet on stove top for 3 minutes",
      "Flip steak and bake for 4 minutes",
      "* Save leftover veggies, minus cilantro, in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Chocolate Candy",
    image: "../images/chocolate_candy.jpg",
    type: ["Dessert"],
    ingredients: [
      "1/3 c honey/maple syrup",
      "3/4 c cacao",
      "1/8 tsp salt",
      "1 tsp vanilla",
      "3/4 c coconut oil",
    ],
    steps: [
      "In a pan, on ow heat, add all ingredients on low heat",
      "Once all well mixed, pour into mold and cool in fridge",
    ],
  },
  {
    name: "Chocolate Chocolate Peanut Butter Chip Cookies",
    image: "../images/chocolate_cookies.jpg",
    type: ["Dessert"],
    ingredients: [
      "1 egg",
      "1 c flour",
      "1 tsp baking soda",
      "3/4 c brown sugar",
      "1/3 c cacao powder",
      "1/4 c granulated sugar",
      "1 tsp salt",
      "1/2 c chocolate chips",
      "1/2 c peanut butter chips",
      "1 tsp vanilla",
      "1 tbsp instant coffee",
      "1/2 c butter",
    ],
    steps: [
      "Mix all the dry ingredients then add all the wet ingredients",
      "Add to freezer bag and flatten",
      "with a butter knife indent a 6 x 4 grid and place bag in freezer",
      "From frozen: Preheat oven to 375F",
      "Bake for 8 1/2 minutes",
    ],
  },
  {
    name: "Chocolate Rice Krispies",
    image: "../images/chocolate_rice_krispies.jpg",
    type: ["Dessert"],
    ingredients: [
      "1 bag mini marshmallows",
      "6 tbsp butter",
      "4 oz chocolate bar",
      "6 c rice krispies",
      "1/4 c cacao",
    ],
    steps: [
      "Add butter and marshmallow to flat bottom pan",
      "Mix in the rice krispies and cacao and cook on low heat",
      "Put in a glass pan, squish down, and cool",
      "Melt chocolate bar and drizzle over rice krispies",
    ],
  },
  {
    name: "Chuletas and Tostones",
    image: "../images/chuletas_and_tostones.jpg",
    type: ["Main", "Friday_Favorites"],
    ingredients: [
      "6 platanos",
      "2 c olive oil",
      "2 garlic bulbs",
      "1/3 c avocado oil",
      "pepper",
      "3 chuletas",
      "salt",
      "oil of choice: butter, tallow, ghee",
    ],
    steps: [
      "Peel platanos and chop into 1 inch cubes",
      "Heat olive oil in pan",
      "Add platanos flat bottom in pan",
      "Fry for 3 minutes each side",
      "Remove platanos from oil and place them on paper towel to cool",
      "Reheat pan",
      "Flatten platanos and add to oil",
      "Fry for 2 minutes each side",
      "Set oven to 450F",
      "Peel and chop garlic",
      "Add garlic, salt, pepper, and avocado oil to a small bowl",
      "Fry chuletas in oil and salt for 3 minutes",
      "Flip and bake for 3 minutes",
      "* chuleta temp: 145F",
    ],
  },
  {
    name: "Dippy Eggs",
    image: "../images/dippy_eggs.jpg",
    type: ["Breakfast"],
    ingredients: ["sliced bread", "eggs", "salt", "butter"],
    steps: ["toast bread and add butter", "fry eggs in butter and add salt"],
  },
  {
    name: "Dutch Oven Beef Stew",
    image: "../images/dutch_oven_beef_stew.jpg",
    type: ["Main"],
    ingredients: [
      "2 lb beef stew meat",
      "1 1/2 tbsp garlic powder",
      "2 tsp onion powder",
      "1 tsp chili powder",
      "1/8 tsp smoked paprika",
      "1 tsp salt",
      "1/4 tsp black pepper",
      "1/4 tsp cinnamon",
      "3 tbsp honey",
      "3 brown potatoes",
      "1 yellow onion",
      "2 carrots",
      "4 celery stalks",
      "1 Gal freezer bag of frozen veggies",
      "2 tbsp salt",
      "3 qts Water",
    ],
    steps: [
      "Place frozen veggies, 2 tbsp salt, 3 qts water in pot and boil for at least 2 hrs",
      "Strain and save 2 c for this recipe and save the broth",
      "Mix dry ingredients and pat on the sides of the beef",
      "Drizzle honey on both sides",
      "Marinade until ready to cook",
      "Set oven to 350F",
      "Sear all sides of beef in dutch oven then set aside",
      "Add 1 c of broth to remove burnt pieces on bottom of dutch oven",
      "Add the beef and add the veggies around",
      "Add 1 c of broth",
      "Put in oven for 20 minutes per lb",
      "Remove from oven and add potatoes and enough broth to cover",
      "Put back in oven for 20 minutes",
      "* Beef temp: 145F",
    ],
  },
  {
    name: "Fried Tacos",
    image: "no image found",
    type: ["Main", "Friday_Favorites"],
    ingredients: [
      "2 tsp salt",
      "1 2/3 cup 100F water",
      "2 1/2 c masa harina",
      "1 lb ground beef",
      "2 tomatoes",
      "1/4 c red onion",
      "8 oz block of pepper jack cheese",
      "Lettuce",
      "Olive oil",
    ],
    steps: [
      "Mix 2 tsp salt, 1 2/3 cup 100F water, 2 1/2 c masa harina together with a fork in a bowl",
      "Knead until smooth",
      "Form 12 1 1/2 inch balls",
      "Cover and rest for 1 hr",
      "Chop red onion, tomato, and lettuce and set aside in a bowl",
      "Shred cheese and set aside in a bowl",
      "Cook ground beef in pan, drain oil, and set aside in a bowl",
      "Heat oil to 325F in a flat bottom pan",
      "Flatten masa ball and fry one side for 1 minute and the other for 50 sec",
      "Fold in half and set aside to cool",
      "* Save all leftover veggies in a 1 gal freezer bag for future broth",
    ],
  },

  {
    name: "Masa Tacos",
    image: "no image found",
    type: ["Main"],
    ingredients: ["2 tsp salt", "1 2/3 cup 100F water", "2 1/2 c masa harina"],
    steps: [
      "Mix all together with a fork in a bowl",
      "Knead until smooth",
      "Form 12 1 1/2 inch balls",
      "Rest for at least 30 minutes",
      "Heat electric griddle on high",
      "Flatten each ball and cook for 2 minutes each side",
    ],
  },
  {
    name: "Garlic Aioli",
    image: "../images/chicken_garlic_aioli_tacos.jpg",
    type: ["Sauce"],
    ingredients: [
      "5 tbsp mayo",
      "1 tbsp basil",
      "2 garlic bulbs",
      "2 tomatoes",
    ],
    steps: [
      "Chop garlic",
      "Chop tomatoes",
      "Add all to a bowl and mix",
      "Let sit for at least 15 minutes",
      "* Save all leftover veggies in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Guacamole",
    image: "../images/guacamole.jpg",
    type: ["Side"],
    ingredients: [
      "1 bunch of cilantro",
      "1 lime",
      "3 avocados",
      "2 tomatoes",
      "1/4 c red onion",
    ],
    steps: [
      "Slice avocados and mash in a bowl",
      "Roll lime, slice in half and squeeze juice into bowl",
      "Chop red onion, tomato, and 1/2 bunch of cilantro and add to bowl",
      "* Save leftover veggies, minus cilantro, in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Veggie Broth",
    image: "no image found",
    type: ["Sauce"],
    ingredients: [
      "1 Gal freezer bag of frozen veggies",
      "2 tbsp salt",
      "3 qts Water",
    ],
    steps: [
      "Place all in pot and boil for at least 2 hrs",
      "Strain and save broth",
    ],
  },
  {
    name: "English Muffins(CICD)",
    image: "../images/english_muffins.jpg",
    type: ["Bakery"],
    ingredients: [
      "1 c soft white flour",
      "227g whole milk greek yogurt",
      "2 tsp baking powder",
      "1 tsp salt",
      "1 tsp sugar",
    ],
    steps: [
      "Set oven to 400F",
      "In a bowl mix flour, baking powder, sugar, and salt",
      "Add yogurt and mix with fork",
      "Knead with oiled hands for 5 minutes",
      "Rest for 5 minutes",
      "Add oil to hands and create 3 english muffin shapes",
      "Add butter to pan and place muffins in pan",
      "Cook one side for 7 minutes and the other side for 5 minutes",
    ],
  },
  {
    name: "Fathers Day Special",
    image: "../images/fathers_day_special.jpg",
    type: ["Main"],
    ingredients: [
      "~2lb live lobster",
      "Ghee or 1 stick of butter",
      "1 lb clams",
      "1 lb crab legs",
    ],
    steps: [
      "Bring water to a boil in a pot large enough to fit the whole lobster",
      "Heat oven to 425F",
      "Bake frozen crab legs for 15 minutes",
      "Heat oven to 475F and add clams for 15 minutes",
      "Add lobster to boiling water",
      "Once water begins to boil again leave lobster in for 10 minutes for the 1st lb and 3 minutes for every lb after",
      "Melt butter on low heat",
      "Turn off the heat and remove the top foam",
      "Slowly pour the clear part of the melted butter into a bowl",
    ],
  },
  {
    name: "Flour Tortilla",
    image: "../images/flour_tortilla.jpg",
    type: ["Side"],
    ingredients: [
      "2 c white flour",
      "3/4 c water",
      "3 tbsp avocado oil",
      "1/2 tsp salt",
    ],
    steps: [
      "Heat water to 110F",
      "In a bowl mix, flour, water, oil, and salt until it looks like a rough dough ball",
      "Rest for 5 minutes",
      "Flour counter and knead dough until smooth",
      "Rest for 5 minutes",
      "Make 1 1/2 inch balls",
      "Heat griddle on max",
      "Flatten dough ball and place on griddle for 30 seconds each side",
    ],
  },
  {
    name: "French Toast",
    image: "../images/french_toast.jpg",
    type: ["Breakfast"],
    ingredients: [
      "sliced bread",
      "1 egg/2 slices of bread",
      "1/4 c milk/1 egg",
    ],
    steps: ["Mix egg and milk in a bowl", "Dip bread in egg dip"],
  },
  {
    name: "Grape Jelly",
    image: "../images/grape_jelly.jpg",
    type: ["Jam"],
    ingredients: [
      "1 lb black or red seedless grapes",
      "3 tbsp lemon juice",
      "2/3 c agave",
      "1 mason jar for storage",
    ],
    steps: [
      "Blend grapes",
      "Set oven to 200F",
      "Add grapes, lemon, and agave to a pot on medium heat",
      "Turn off stove and place jar in oven for 20 min",
      "Boil grapes while stirring every 10 minutes until thickened about 30 minutes",
      "Place in jar, seal, and let cool",
    ],
  },
  {
    name: "Meat Kabobs",
    image: "../images/kabobs.jpg",
    type: ["Main"],
    ingredients: [
      "1 lb of 1 inch chunk meat",
      "2 yellow zucchini",
      "3 multicolored peppers",
      "1 yellow onion",
    ],
    steps: [
      "Chop all veggies into 1 inch chunks",
      "Add to skewer in rotation of meat and veggie",
    ],
  },
  {
    name: "Pasta",
    image: "../images/lemon_chicken_mushroom.jpg",
    type: ["Side"],
    ingredients: ["1 c soft white flour", "2 eggs", "3 tbsp salt"],
    steps: [
      "Pour flour on counter and create a well in the center",
      "Add eggs to well and scramble with fork",
      "Slowly add surrounding flour",
      "Knead until smooth - ~5 minutes",
      "Let rest for 1 hr",
      "Boil water half way up pot and add salt",
    ],
  },
  {
    name: "Lemon Chicken Mushroom",
    image: "../images/lemon_chicken_mushroom.jpg",
    type: ["Main"],
    ingredients: [
      "3 portobello mushrooms",
      "2 chicken breast",
      "2 lemons - 4tbsp juice",
      "1 tbsp oregano",
      "4 garlic cloves",
      "1/2 tsp salt",
    ],
    steps: [
      "Chop chicken into 1/2 inch cubes",
      "Place chicken in a bowl with lemon, oregano, garlic, and salt",
      "Marinade for 20 minutes",
      "Set oven to 350F",
      "In a pan cook chicken until half cooked",
      "Fill mushrooms with chicken",
      "Bake for 20 minutes",
    ],
  },
  {
    name: "Lotion",
    image: "../images/lotion.jpg",
    type: ["Misc"],
    ingredients: [
      "3/4 c shea butter",
      "1/4 c coconut oil",
      "1 tbsp arrowroot powder",
      "5 drops vitamin E",
      "15 drops vanilla essential oil",
      "15 drops grapefruit essential oil",
    ],
    steps: [
      "Create a double boiler with a smaller glass bowl in a bigger glass bowl",
      "Fill bigger bowl with enough hot water to almost cover the smaller bowl",
      "Melt shea butter and coconut oil in smaller bowl",
      "Place smaller bowl in freezer for 20 minutes or until lotion density",
      "Add essential oils and mix with a hand mixer",
      "Add the arrowroot powder a little at a time with hand mixer",
      "Add to a air tight glass jar, cover and let cool",
    ],
  },
  {
    name: "Mac and Cheese(CICD)",
    image: "../images/mac_and_cheese_cicd.jpg",
    type: ["Main", "Holiday_Thanksgiving"],
    ingredients: [
      "8 oz elbows",
      "1/2 tbsp olive oil",
      "1/2 c butter",
      "1/6 c flour",
      "3 c milk",
      "1/2 c heavy whipping cream",
      "2 c shredded sharp cheddar smoked",
      "4 oz cream cheese",
      "1/2 c shredded parmesan",
      "1/2 c panko crumbs",
    ],
    steps: [
      "Boil elbows 3 minutes less than packaging and drain",
      "Toss elbows in oil and set aside",
      "In a large pot whisk over low heat slowly, butter, flour, milk, cream, cream cheese, and cheddar",
      "Stir in elbows to pot and pour in baking dish",
      "Mix parmesan and panko crumbs and put on top of elbows",
      "Bake at 350F for 25 minutes",
      "Broil one level lower than highest in oven for 5 minutes",
    ],
  },
  {
    name: "Shrimp Mofongo 3 Ways",
    image: "../images/mofongo.jpg",
    type: ["Main", "Friday_Favorites"],
    ingredients: [
      "6 platanos",
      "2 lb shrimp",
      "4 garlic bulbs",
      "2 tbsp olive oil",
      "avocado oil",
      "1 tbsp butter",
      "2 tsp salt",
    ],
    steps: [
      "1/3 garlic in a pan in butter until golden brown",
      "1/3 garlic raw",
      "1/3 garlic in a glass dish in olive oil, roast in oven at 350F for 20 minutes",
      "Chop platanos into 1 inch cubes",
      "Deep fry in olive oil until golden brown",
      "Place platanos in a bowl and set aside",
      "Cook shrimp and drain water",
      "Add pan roasted garlic to shrimp",
      "Mash platanos (add avocado oil if too dry)",
      "Add all plus salt to bowl",
    ],
  },
  {
    name: "Paella",
    image: "../images/paella.jpg",
    type: ["Main", "Friday_Favorites"],
    ingredients: [
      "frozen shrimp",
      "frozen shelled scallops",
      "frozen shelled mussels",
      "2 jalapenos",
      "2 tomatoes",
      "1/2 c white rice",
      "1 tsp onion powder",
      "1 tsp garlic powder",
      "1 tsp oregano",
    ],
    steps: [
      "Add shrimp, scallops, and mussels to a large pot",
      "Once seafood is defrosted add rice, onion powder, garlic powder, oregano, 1/4 c water, 1 chopped tomato, and chopped jalapenos with seeds",
      "Cook for 20 minutes on low heat",
      "Garnish with 1 chopped tomato",
      "* Save all leftover veggies in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Peanut Butter Oats",
    image: "../images/peanut_butter_oats.jpg",
    type: ["Dessert"],
    ingredients: [
      "1 c rolled oats",
      "3/4 c soft white flour",
      "1 1/2 tsp baking powder",
      "1/2 tsp cinnamon",
      "1/8 tsp salt",
      "1 egg white",
      "1 tsp vanilla",
      "1/3 c peanut butter",
      "1/2 c honey",
      "5 tbsp milk",
    ],
    steps: [
      "Set oven to 300F",
      "In a bowl 1 mix oats, flour, baking powder, cinnamon, and salt",
      "In bowl 2 mix egg and vanilla, stir in peanut butter, stir in honey, stir in milk",
      "Stir in bowl 1 to bowl 2",
      "Place in 8 inch pan and bake for 12 min",
      "Rest for 4 hrs",
    ],
  },
  {
    name: "Pernil",
    image: "../images/pernil.jpg",
    type: ["Main", "Holiday_Christmas"],
    ingredients: [
      "1/4 c olive oil",
      "4 lb pork shoulder",
      "1 tbsp adobo",
      "2 sazon packets",
      "1/2 tbsp black pepper",
      "1/2 tbsp thyme",
      "1 tbsp garlic powder",
      "1 tbsp onion powder",
    ],
    steps: [
      "Mix all spices and oil in a bowl",
      "Stab pork with knife and add mixture all over pork",
      "Let marinade in the fridge skin side down overnight",
      "Take out of fridge 1 hour before cooking",
      "Set oven to 275F and bake pernil skin side down for 2 hrs covered in foil",
      "Remove foil and bake for another 2 hrs at 350F skin side up",
    ],
  },
  {
    name: "Pie Crust",
    image: "../images/pie_crust.jpg",
    type: ["Bakery"],
    ingredients: [
      "2 c soft white flour",
      "1/4 tsp salt",
      "3 tbsp cold butter",
      "1/4 c + 3 tbsp cold coconut oil",
      "1/4 c ice water",
    ],
    steps: [
      "In a the stand mixer bowl whisk flour and salt",
      "Place in fridge for 20 min",
      "Whisk in cubed butter mix for 1 min on lvl 1",
      "Whisk in coconut oil at lvl 4, should look like dry cookie dough",
      "Replace whisk with dough hook and slowly add the ice water until it looks like wet cookie dough",
      "Roll into a ball and place in fridge for 2 hrs",
      "Flour counter, roll out dough, place in pan and leave in fridge for 30 min",
      "Add filling",
      "Place in oven at 425F for 15 min",
      "Lower oven to 350 for 35 min",
    ],
  },
  {
    name: "Pizza Crust(1-10 inch)",
    image: "../images/pizza_crust.jpg",
    type: ["Bakery"],
    ingredients: [
      "2/3 c warm water",
      "1/4 tsp yeast",
      "1/2 tsp honey",
      "1 1/2 tsp salt",
      "1 1/2 c soft white flour",
      "2 tbsp avocado oil",
      "2 tsp garlic powder",
      "1/2 tsp oregano",
    ],
    steps: [
      "Mix water, yeast, honey, 1 tsp salt and let sit for 5 minutes",
      "Add flour and knead for 2 minutes",
      "Cover and rest for 5 hours",
      "Fold over 8 times and rest or another 2 hours",
      "Roll out pizza",
      "Set oven to 550F and bake for 10 minutes",
      "Mix in a small bowl 1/2 tsp salt, avocado oil, garlic powder, and oregano",
      "Brush on crust",
    ],
  },
  {
    name: "Garlic Tostones",
    image: "../images/garlic_tostones.jpg",
    type: ["Side"],
    ingredients: [
      "6 platanos",
      "2 c olive oil",
      "2 garlic bulbs",
      "1/3 c avocado oil",
      "salt",
      "pepper",
    ],
    steps: [
      "Peel platanos and chop into 1 inch cubes",
      "Heat olive oil in pan",
      "Add platanos flat bottom in pan",
      "Fry for 3 minutes each side",
      "Remove platanos from oil and place them on paper towel to cool",
      "Peel and chop garlic",
      "Add garlic, avocado oil, salt, and pepper to a small bowl",
      "Reheat pan",
      "Flatten platanos and add to oil",
      "Fry for 2 minutes each side",
    ],
  },
  {
    name: "Garlic Sauce",
    image: "../images/garlic_sauce.jpg",
    type: ["Sauce"],
    ingredients: ["2 garlic bulbs", "1/3 c avocado oil", "salt", "pepper"],
    steps: ["Peel and chop garlic", "Add all to a small bowl"],
  },
  {
    name: "Pollo Guisado",
    image: "../images/pollo_guisado.jpg",
    type: ["Main"],
    ingredients: [
      "4 chicken thighs",
      "6 drumsticks",
      "4 brown potatoes",
      "6 carrots",
      "3/4 c sofrito",
      "3/4 c tomato paste",
      "Veggie broth recipe",
      "1/4 c olive oil",
      "2 tbsp salt",
    ],
    steps: [
      "Make veggie broth recipe",
      "Chop chicken and put in pot",
      "Add broth, oil, sofrito, salsa",
      "Bring to boil",
      "Add 1 inch chopped potatoes, salt, and carrots",
      "Bring to boil and remove after 20 minutes",
      "* Save all leftover veggies in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Sofrito",
    image: "../images/pollo_guisado.jpg",
    type: ["Sauce"],
    ingredients: [
      "1 yellow onion",
      "1 green pepper",
      "1 garlic bulb",
      "1 bunch cilantro",
    ],
    steps: [
      "Chop and add all to blender",
      "* Save leftover veggies, minus cilantro, in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Rotisserie Chicken",
    image: "../images/rotisserie_chicken.jpg",
    type: ["Main", "Friday_Favorites"],
    ingredients: [
      "~5 lb whole chicken",
      "baking string",
      "1 tsp thyme",
      "1/4 c olive oil",
      "1 tsp paprika",
      "1 tsp oregano",
      "1 tsp onion powder",
      "2 tsp garlic powder",
      "1 packet sazon",
      "1 tsp adobo",
      "rotisserie machine",
    ],
    steps: [
      "Mix all spices and oil in a bowl",
      "Put mixture under skin of chicken",
      "Use the baking string to tie the legs, arms, and around whole chicken",
      "Marinade for 1 hr and remove from fridge 1 hour before baking",
      "Place in machine and air fry for 15 minutes/lb",
      "* Chicken temp: 165F",
    ],
  },
  {
    name: "Salmon",
    image: "../images/salmon.jpg",
    type: ["Main"],
    ingredients: ["salmon", "butter", "salt", "basil", "onion powder"],
    steps: [
      "Set oven to 400F",
      "Add to salmon, salt, onion, basil, and butter",
      "Bake for 10 minutes",
      "* Salmon temp: 145F",
    ],
  },
  {
    name: "Sausage Boats",
    image: "../images/sausage_boats.jpg",
    type: ["Main", "Friday_Favorites"],
    ingredients: [
      "1/2 tbsp yeast",
      "3/4 c 115F water",
      "1 3/4 c soft white flour",
      "1/4 c hard white flour",
      "1/8 c olive oil",
      "1/8 c honey",
      "1 tsp salt",
      "8 olives",
      "1 tomato",
      "1 cucumber",
      "1/4 cup chopped red onion",
      "1 lb sausage",
      "mayo",
      "ketchup",
      "spicy mustard",
    ],
    steps: [
      "Mix yeast and water in a bowl",
      "Stir until yeast is dissolved",
      "Add 1 1/2 c soft white flour and mix",
      "Cover and rest for 20 minutes or until bubbly",
      "Add remaining soft white flour, honey, oil, and salt",
      "Knead in stand mixer until dough ball forms, about 5 minutes",
      "If dough is sticking to sides slowly add hard white flour a small amount at a time",
      "Flour counter and cut dough in half",
      "Fold into thirds then roll the long way and pinch the ends under",
      "Create an aluminum wall high enough to separate the 2 halves",
      "Add parchment paper to each half",
      "Bake at 350 for 25 minutes",
      "Create hotdog shapes with sausage and cook",
      "Let bread cool while cooking sausage",
      "Chop all veggies",
      "Scoop out insides of bread",
      "* Save all leftover veggies in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Shawns Chili",
    image: "../images/shawns_chili.jpg",
    type: ["Main", "Friday_Favorites"],
    ingredients: [
      "2 lbs ground beef",
      "6 tomatoes chopped",
      "16 oz red kidney beans(black beans recipe)",
      "2 corn",
      "2 garlic bulbs",
      "shredded cheese",
      "1 onion",
      "3 peppers",
      "2 jalapenos plus seeds",
      "2 tbsp salt",
    ],
    steps: [
      "Chop all veggies",
      "Add to large pot",
      "Add beans and bean water to pot",
      "Cook on low",
      "* Save all leftover veggies in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Shawns Lemonade",
    image: "../images/shawns_lemonade.jpg",
    type: ["Drink"],
    ingredients: ["1 cup water", "2 tbsp agave", "3 tbsp lemon juice", "ice"],
    steps: ["Stir water, agave, and lemon juice in a cup", "Fill cup with ice"],
  },
  {
    name: "Shawns Tea(2)",
    image: "../images/shawns_tea.jpg",
    type: ["Drink"],
    ingredients: [
      "4 tbsp black tea",
      "2 lemons",
      "6 tbsp agave",
      "ice",
      "3 cups boiling water",
    ],
    steps: [
      "Seep tea for 5 minutes in water",
      "Pour 1 cup of tea in glass",
      "Stir in 3 tbsp of agave one at a time",
      "Stir in 2 tbsp of lemon juice",
      "Add ice up to 1 inch below rim of glass",
      "Add 1/2 c tea and stir",
      "Add 1 tbsp lemon juice and stir",
    ],
  },
  {
    name: "Shepherds Pie",
    image: "../images/shepherds_pie.jpg",
    type: ["Main"],
    ingredients: [
      "2 lbs ground beef",
      "3 brown potatoes",
      "1 carrot stick",
      "1/3 yellow onion",
      "1/3 green pepper",
      "2 packets sazon",
      "4 layers adobo",
    ],
    steps: [
      "Set oven to 350F",
      "Boil 1/2 large pot with water",
      "Chop potatoes into 1 inch cubes and add to boiling water",
      "Boil for 20 minutes",
      "Cook ground beef, drain, set aside",
      "Chop carrot into coins and cook in pot that held the ground beef",
      "Once carrots are a little charred add onion and green pepper",
      "Once veggies look soft add the sazon, adobo, and ground beef",
      "Add to glass dish and flatten",
      "Mash potatoes and flatten on top of beef",
      "Bake for 30 minutes",
      "* Save all leftover veggies in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Shoulder Roast",
    image: "../images/shoulder_roast.jpg",
    type: ["Main"],
    ingredients: [
      "2 lbs frozen beef bones",
      "1 gal of water",
      "2 tbsp onion powder",
      "3 tbsp salt",
      "1/2 tbsp thyme",
      "1/2 tbsp smoked paprika",
      "4 lb shoulder roast",
    ],
    steps: [
      "Bake bones in oven at 400F for 1 hr",
      "Add bones, bone drippings, 2 tbsp salt, and 1 gal water to pot",
      "Boil then simmer for 4 hrs",
      "Add all spices to pot",
      "Stab roast with fork and add to pot",
      "Bake for 30 minutes, flip roast, and finish baking for 30 min",
      "* Roast temp: 145F",
    ],
  },
  {
    name: "Spaghetti Squash and Meatballs",
    image: "../images/spaghetti_and_meatballs.jpg",
    type: ["Main"],
    ingredients: [
      "Spaghetti squash",
      "1 lb ground beef",
      "1/2 tsp basil",
      "1/2 tsp parsley",
      "2 tsp salt",
      "8 tomatoes",
      "1 tbsp + 1 tsp garlic powder",
      "1 tbsp + 1 tsp onion powder",
      "1/2 tbsp honey",
      "2 tsp chili flakes",
      "1/2 tbsp oregano",
    ],
    steps: [
      "Mix ground beef, 1 tsp chili pepper flakes, 1 tsp garlic powder, 1 tsp onion powder, basil, parsley, and salt in a pot by hand",
      "Create 1 inch balls",
      "Sear all sides in a large pan",
      "Remove core from tomatoes and blend",
      "Add tomatoes, 1 tbsp garlic powder, 1 tbsp onion powder, 1/2 tbsp honey, 1 tsp chili flakes, and oregano to pot and bring to boil",
      "Simmer for 30 minutes",
      "Set oven to 400F",
      "Cut spaghetti squash in half the long way",
      "Scoop out the seeds and drizzle olive oil",
      "Add salt and pepper",
      "Place shell side up on baking pan",
      "Bake for 30 minutes",
      "Once cooled, shred with fork",
      "* Save all leftover veggies in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Spaghetti and Meatballs",
    image: "../images/spaghetti_and_meatballs.jpg",
    type: ["Main"],
    ingredients: [
      "1 c soft white flour",
      "2 eggs",
      "3 tbsp + 2 tsp salt",
      "1 tbsp olive oil",
      "1 lb ground beef",
      "1/2 tsp basil",
      "1/2 tsp parsley",
      "8 tomatoes",
      "1 tbsp + 1 tsp garlic powder",
      "1 tbsp + 1 tsp onion powder",
      "1/2 tbsp honey",
      "2 tsp chili flakes",
      "1/2 tbsp oregano",
    ],
    steps: [
      "Pour flour on counter and create a well in the center",
      "Add eggs to well and scramble with fork",
      "Slowly add surrounding flour",
      "Knead until smooth - ~5 minutes",
      "Let rest for 1 hr",
      "Fill large pot half way with water to boil",
      "Cut pasta into 8 pieces",
      "Roll out each piece and flatten with pasta machine",
      "Pass through spaghetti part of machine",
      "Once water is boiling add salt and pasta",
      "Boil for 3 minutes",
      "Drain water and add olive oil",
      "Remove core from tomatoes and blend",
      "Add tomatoes, 1 tbsp garlic powder, 1 tbsp onion powder. honey, 1 tsp chili flakes, and oregano to pot and bring to boil",
      "Simmer for 30 minutes",
      "Mix ground beef, 1 tsp chili flakes, 1 tsp garlic powder, 1 tsp onion powder, 1/2 tsp basil, 1/2 tsp parsley, and 2 tsp salt in a pot by hand",
      "Create 1 inch balls",
      "Sear all sides in a large pan",
      "Make meatball recipe and add to sauce",
      "* Save all leftover veggies in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Meatballs",
    image: "../images/spaghetti_and_meatballs.jpg",
    type: ["Side"],
    ingredients: [
      "2 lb ground beef",
      "2 tsp chili pepper flakes",
      "1 tbsp garlic powder",
      "1 tbsp onion powder",
      "1/2 tbsp basil",
      "1/2 tbsp parsley",
      "2 tsp salt",
    ],
    steps: [
      "Mix all in a bowl by hand",
      "Create 1 inch balls",
      "Sear all sides in a large pan",
      "* Meatball temp: 145F",
    ],
  },
  {
    name: "Spaghetti",
    image: "../images/spaghetti.jpg",
    type: ["Side"],
    ingredients: [
      "1 c soft white flour",
      "2 eggs",
      "1 1/2 tbsp salt",
      "1 tbsp olive oil",
    ],
    steps: [
      "Pour flour on counter and create a well in the center",
      "Add eggs to well and scramble with fork",
      "Slowly add surrounding flour",
      "Knead until smooth - ~5 minutes",
      "Let rest for 1 hr",
      "Fill large pot half way with water to boil",
      "Cut pasta into 8 pieces",
      "Roll out each piece and flatten with pasta machine",
      "Pass through spaghetti part of machine",
      "Once water is boiling add salt and pasta",
      "Boil for 3 minutes",
      "Drain water and add olive oil",
    ],
  },
  {
    name: "Spanish Rice",
    image: "../images/spanish_rice.jpg",
    type: ["Side"],
    ingredients: [
      "2 c water",
      "1/2 c black beans",
      "1 tsp salt",
      "1 c white rice",
      "1 tbsp coconut oil",
      "1 packet sazon",
      "2 tsp adobo",
      "1 can tomato sauce",
      "1 1/4 c water",
      "1 tbsp sofrito",
    ],
    steps: [
      "Add 2 c water, 1 tsp salt, and black beans to pot and bring to boil",
      "Simmer for 2 hrs",
      "Add rice coconut oil, sazon, adobo, tomato sauce, 1 1/4 c water, and sofrito to pot and bring to boil",
      "Simmer for 40 minutes",
    ],
  },
  {
    name: "White Rice",
    image: "../images/white_rice.jpg",
    type: ["Side"],
    ingredients: [
      "1 c white rice",
      "2 tsp salt",
      "1 tbsp coconut oil",
      "1 1/4 c water",
    ],
    steps: [
      "Add water, salt, oil, and rice to pot",
      "Bring to boil then simmer for 25 minutes",
    ],
  },
  {
    name: "Steak",
    image: "../images/steak_potato.jpg",
    type: ["Main"],
    ingredients: ["1 lb steak", "Salt"],
    steps: [
      "Set oven to 450F",
      "Add a good layer of salt all over steak",
      "Cook steak on cast iron skillet on stove top for 3 minutes",
      "Flip steak and bake for 4 minutes",
    ],
  },
  {
    name: "Stove Cleaner",
    image: "../images/stove_cleaner.jpg",
    type: ["Misc"],
    ingredients: ["1 c baking soda", "1/4 c liquid soap", "hydrogen peroxide"],
    steps: [
      "Mix all into a paste",
      "Scrub onto stove",
      "Let sit for 30 minutes",
    ],
  },
  {
    name: "Strawberry Jam",
    image: "../images/strawberry_jam.jpg",
    type: ["Jam"],
    ingredients: [
      "1 lb strawberries",
      "5 tbsp lemon juice",
      "2/3 c agave",
      "1 mason jar for storage",
    ],
    steps: [
      "Blend strawberries",
      "Set oven to 200F",
      "Add strawberries, lemon, and agave to a pot on medium heat",
      "Turn off stove and place jar in oven for 20 min",
      "Boil strawberries while stirring every 10 minutes until thickened about 30 minutes",
      "Place in jar, seal, and let cool",
    ],
  },
  {
    name: "Stuffed Cabbage",
    image: "../images/stuffed_cabbage.jpg",
    type: ["Main"],
    ingredients: [
      "1 cabbage",
      "1 yellow onion",
      "cilantro",
      "2 tomatoes",
      "1/2 c white rice",
      "1/2 tbsp coconut oil",
      "1/2 + 1/8 c water",
      "tomato paste",
      "1 lb ground beef",
      "1 tsp garlic powder",
      "1 tsp oregano",
      "1 tsp red chili flakes",
      "1 1/2 tbsp salt",
      "1 tsp pepper",
      "1 tsp smoked paprika",
    ],
    steps: [
      "Add water, 1/2 tbsp salt, coconut oil, and rice to pot",
      "Bring to boil then simmer for 20 minutes",
      "Boil water in a large pot",
      "Add whole cabbage to pot and boil for 20 minutes",
      "Set oven to 375F",
      "In a large bowl add onion, cilantro, rice, ground beef, garlic powder, oregano, chili flakes, 1 tbsp salt, pepper, and smoked paprika and combine with hands",
      "Remove cabbage from boiling water and place in a bowl of ice water",
      "Peel one leaf of cabbage at a time and fill with ground beef",
      "Continue to roll up into a small egg roll shape and place in glass dish",
      "In blender add tomatoes and tomato paste",
      "Pour tomato sauce over cabbage rolls",
      "Bake for 30 minutes",
      "* Cabbage temp: 145F",
      "* Save leftover veggies, minus cilantro, in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Stuffed Chicken",
    image: "../images/stuffed_chicken.jpg",
    type: ["Main"],
    ingredients: [
      "2 chicken breast",
      "2 tomato",
      "1 bunch of spinach",
      "1 bulb of garlic",
      "2 shallot",
      "2 tsp salt",
      "1 tsp onion powder",
      "1 tsp garlic powder",
      "1 tsp oregano",
      "1 tbsp avocado oil",
    ],
    steps: [
      "Chop spinach, tomato, garlic, and shallots",
      "set oven to 400F",
      "In pan add olive oil and garlic",
      "Once garlic has started to turn golden brown add spinach",
      "Once spinach has withered turn off stove and leave in pan",
      "In a small bowl mix salt, onion powder, garlic powder, and oregano",
      "Layer the bottom of a glass baking dish with 1/3 of the spice mix",
      "Cut chicken breast in half like a taco",
      "Add 1/3 of spice mix to inside of chicken",
      "Layer most of spinach, most tomatoes, and most shallots inside each chicken",
      "Close chicken, use toothpicks if it does not stay closed",
      "Add remaining spice mix",
      "Add the remaining spinach, tomato, and shallot to top of each chicken",
      "Bake for 30 minutes",
      "* Chicken temp: 165F",
      "* Save all leftover veggies in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Sushi",
    image: "../images/sushi.jpg",
    type: ["Main"],
    ingredients: [
      "seaweed",
      "1/2 c white rice",
      "1 tsp salt",
      "1/2 tbsp coconut oil",
      "3/4 c water",
      "shrimp",
      "1 cucumber",
      "1 avocado",
    ],
    steps: [
      "Add water, salt, oil, and rice to pot",
      "Bring to boil then simmer for 25 minutes",
      "Cook shrimp",
      "Chop shrimp, cucumber, and avocado into thin strips",
      "Lay seaweed and add a thin layer of rice",
      "Add shrimp, cucumber, and avocado in a line on top of rice",
      "Roll seaweed tightly and slice into 1 inch pieces",
    ],
  },
  {
    name: "Sweet Potato Casserole",
    image: "../images/sweet_potato_casserole.jpg",
    type: ["Holiday_Thanksgiving"],
    ingredients: [
      "5 sweet potatoes",
      "1/2 c brown sugar",
      "1/4 c butter",
      "3 tbsp orange juice",
      "1 tsp ground cinnamon",
      "1 10.5 oz mini marshmallows",
    ],
    steps: [
      "Boil sweet potatoes and mash in mixing bowl",
      "Stir in brown sugar, butter, orange juice, and cinnamon to bowl",
      "Add marshmallows on top and bake at 350F for 30 minutes",
    ],
  },
  {
    name: "Tomato Sauce",
    image: "../images/tomato_sauce.jpg",
    type: ["Sauce"],
    ingredients: [
      "8 tomatoes",
      "1 tbsp garlic powder",
      "1 tbsp onion powder",
      "1/2 tbsp honey",
      "1 tsp chili flakes",
      "1/2 tbsp oregano",
    ],
    steps: [
      "Remove core from tomatoes and blend",
      "Add all ingredients to pot and bring to boil",
      "Simmer for about an hour on med heat or your preferred sauce consistency",
      "* Save all leftover veggies in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Top Round Steak",
    image: "../images/top_round.jpg",
    type: ["Main"],
    ingredients: ["1 lb top round steak", "salt", "olive oil"],
    steps: [
      "Smash steak to soften meat",
      "Add salt and oil and marinade for 2 hours",
      "Put steak in broil safe cooking sheet",
      "Broil each side for 3 minutes",
    ],
  },
  {
    name: "Tortilla Chips",
    image: "../images/tortilla_chips.jpg",
    type: ["Side"],
    ingredients: ["Left over masa", "olive oil", "salt"],
    steps: [
      "Set oven to 350F",
      "Slice masa into triangles and put on pan",
      "Brush olive oil on slices and add salt",
      "Bake for 5 minutes",
    ],
  },
  {
    name: "Waffles(2)",
    image: "../images/waffles_pancakes.jpg",
    type: ["Breakfast"],
    ingredients: [
      "1 c red flour",
      "1 tbsp honey",
      "1/2 tbsp baking powder",
      "1 tsp salt",
      "3/4 c milk",
      "1 egg",
      "1/8 c olive oil",
      "1 tsp vanilla",
    ],
    steps: ["Mix all in a bowl", "Rest for 5 minutes"],
  },
  {
    name: "Pancakes(10)",
    image: "../images/waffles_pancakes.jpg",
    type: ["Breakfast"],
    ingredients: [
      "1 c hard white flour",
      "2 tsp baking powder",
      "1 tsp baking soda",
      "1/2 tsp salt",
      "2 egg",
      "1 c milk",
      "1 tsp vanilla",
      "1 tbsp honey",
    ],
    steps: [
      "Mix all in a bowl",
      "Rest for 10 minutes",
      "Heat pan and pour batter into 4 inch circles",
    ],
  },
  {
    name: "Zucchini Bread",
    image: "../images/zucchini_bread.jpg",
    type: ["Dessert"],
    ingredients: [
      "1 3/4 c hard red flour",
      "1/2 tsp salt",
      "1/2 tsp baking soda",
      "1/2 tsp baking powder",
      "2 tsp cinnamon",
      "1 3/4 c shredded zucchini",
      "2 eggs",
      "1/4 c apple sauce",
      "1/4 c olive oil",
      "1/2 c honey",
      "1/3 c agave",
      "2 tsp vanilla",
    ],
    steps: ["Set oven to 375F", "Mix all ingredients and bake for 1 hr"],
  },
  {
    name: "Taco Dip",
    image: "no image found",
    type: ["Main"],
    ingredients: [
      "1 lb ground beef",
      "2 tsp salt",
      "8 oz cream cheese",
      "shredded lettuce",
      "2 tomatoes",
      "1 can refried black beans",
      "8 oz shredded cheese",
    ],
    steps: [
      "Fully cook ground beef with salt",
      "Drain ground beef and place in 8 inch glass dish",
      "Add a layer of refried beans",
      "Add layer of room temp cream cheese",
      "Add chopped tomatoes, lettuce, and shredded cheese",
      "* Save all leftover veggies in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Chicken Parm",
    image: "no image found",
    type: ["Main"],
    ingredients: [
      "1 c hard white flour",
      "5 tbsp salt",
      "2 tbsp italian seasoning",
      "4 egg",
      "1/3 c milk",
      "1 1/2 c Olive oil",
      "2 chicken breast",
      "mozzarella cheese",
      "Parmesan cheese",
      "1 c soft white flour",
      "8 whole peeled tomatoes",
      "1 tbsp garlic powder",
      "1 tbsp onion powder",
      "1/2 tbsp honey",
      "1 tsp chili flakes",
      "1/2 tbsp oregano",
    ],
    steps: [
      "Remove core from tomatoes and blend",
      "Add blended tomato, 1 tbsp garlic powder, 1 tbsp onion, 1/2 tbsp honey, 1 tsp chili flakes, and 1/2 tbsp oregano to pot and bring to boil",
      "Simmer for about an hour, until sauce looks like tomato sauce",
      "Pour soft white flour on counter and create a well in the center",
      "Add 2 eggs to well and scramble with fork",
      "Slowly add surrounding flour",
      "Knead until smooth - ~5 minutes",
      "Let rest for 1 hr",
      "Boil water half way up pot and add 3 tbsp salt",
      "In a bowl mix hard white flour, 1 1/2 tbsp salt, 1/4 c shredded parmesan, and italian seasoning",
      "In a separate bowl mix 2 eggs and 1/3 c milk",
      "In a flat bottom pan add enough olive oil so chicken is half submerged",
      "Set oven to 450F",
      "Cut chicken breast in half and dip in egg , flour, egg, then flour again",
      "Fry each side of the chicken for 3 minutes",
      "In a glass dish add chicken and 2 slices of mozzarella cheese",
      "Bake for 10 minutes",
      "* Save all leftover veggies in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Marinara Sauce",
    image: "no image found",
    type: ["Sauce"],
    ingredients: [
      "6 whole peeled tomatoes",
      "1/2 c olive oil",
      "1 yellow onion",
      "1/2 tbsp salt",
      "1 garlic bulb",
      "1/2 tbsp oregano",
      "1/2 tbsp basil",
      "1 tsp black pepper",
    ],
    steps: [
      "Blend all",
      "Add to a pot and bring to boil",
      "Simmer for 1 hr/ until sauce is about 1/3 of original volume",
      "Store in mason jar",
      "* Save all leftover veggies in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Shawn Peanut Butter Oatmeal Cookies (CICD)",
    image: "no image found",
    type: ["Dessert"],
    ingredients: [
      "1 c butter",
      "4 c sugar",
      "1/2 tsp salt",
      "1 c milk",
      "1 tsp vanilla",
      "6 c or 18 oz oats",
      "2 1/2 c peanut or 28oz jar",
    ],
    steps: [
      "In one bowl, stir butter, sugar, salt, milk for 4 min after roaring boiling",
      "In a larger bowl, add vanilla, oats, and peanut butter",
      "Stir first bowl into larger bowl",
      "use ice cream scooper to scoop onto parchment paper and refrigerate",
    ],
  },
  {
    name: "Chocolate Foamy Jello Recipe(4)",
    image: "No image found",
    type: ["Dessert"],
    ingredients: [
      "1 box cherry jello",
      "1 box chocolate pudding",
      "milk for pudding",
      "1 tub of cool whip",
      "1 lb strawberries",
    ],
    steps: [
      "Bring cool whip to room temp",
      "Make cherry jello mixed with 1 c boiling water",
      "when dissolved add 1/2 c cold water",
      "Let rest in fridge for 25 min",
      "Whisk in 2 c cool whip",
      "Let rest in fridge for 30 min",
      "Whisk in chopped strawberries to foam",
      "Let rest another 30 min in fridge",
      "Pour foam into cup let set for 2 hrs in fridge",
      "Follow instructions for chocolate pudding using milk",
      "Pour into foam cup and let rest for 2 hrs",
    ],
  },
  {
    name: "Chocolate Frosting",
    image: "no image found",
    type: ["Sauce"],
    ingredients: [
      "1/4 c melted butter",
      "2/3 c cacao powder",
      "1.5 c confectionary sugar",
      "1/6 c milk",
      "1/2 tsp vanilla",
    ],
    steps: ["Mix all in a bowl", "Note: will be runny but not drip off"],
  },
  {
    name: "Chocolate Chocolate Peanut Butter Chip Muffins(6)",
    image: "no image found",
    type: ["Dessert"],
    ingredients: [
      "2 egg",
      "1 c flour",
      "1 tsp baking powder",
      "1/2 tsp baking soda",
      "1/2 c brown sugar",
      "1/3 c cacao powder",
      "2 tbsp granulated sugar",
      "3/4 tsp salt",
      "1/2 c chocolate chips",
      "1/2 c peanut butter chips",
      "1 tsp vanilla",
      "1 tbsp instant coffee",
      "1/2 c butter",
      "1/2 c milk",
    ],
    steps: ["Set oven to 375F", "Mix all ingredients", "Bake for 20 min"],
  },
  {
    name: "Fresh Wings",
    image: "no image found",
    type: ["Main", "Side"],
    ingredients: ["wings", "olive oil"],
    steps: [
      "Add enough oil to pot to cover wings",
      "Once oil reaches 360F add wings",
      "Fry wings for 20 minutes",
    ],
  },
  {
    name: "Frozen Fries",
    image: "no image found",
    type: ["Side"],
    ingredients: ["frozen fries", "olive oil"],
    steps: [
      "Add enough oil to pot to cover fries",
      "Once oil reaches 400F add fries",
      "Fry fries for 10 minutes",
    ],
  },
  {
    name: "Granola",
    image: "no image found",
    type: ["Side"],
    ingredients: [
      "1 c old fashioned rolled oats whole grain",
      "1.5 tbsp honey",
      "1 tbsp vanilla",
    ],
    steps: [
      "Set oven to 275F",
      "Mix in bowl",
      "Spread on cookie sheet",
      "Bake for 20 min",
    ],
  },
  {
    name: "Parfait",
    image: "no image found",
    type: ["Breakfast"],
    ingredients: [
      "1 c old fashioned rolled oats whole grain",
      "2.5 tbsp honey",
      "1 tbsp vanilla",
      "3/4 c greek yogurt",
      "Strawberries",
      "Blackberries",
      "Blueberries",
    ],
    steps: [
      "Set oven to 275F",
      "Mix oats, 1.5 tbsp honey, and vanilla in bowl",
      "Spread on cookie sheet",
      "Bake for 20 min",
      "Let cool then break into crumbles in a bowl",
      "Slice strawberries into 4 pieces",
      "In the bowl you are eating from add yogurt, fruit, granola, and drizzle 1 tbsp honey",
    ],
  },
  {
    name: "Meatballs and Sauce",
    image: "no image found",
    type: ["Side"],
    ingredients: [
      "8 tomatoes",
      "3 tbsp garlic powder",
      "3 tbsp onion powder",
      "1/2 tbsp honey",
      "1 tsp chili flakes",
      "1/2 tbsp oregano",
      "2 lbs ground beef",
      "2 tsp salt",
      "1/2 tbsp basil",
      "1/2 tbsp parsley",
    ],
    steps: [
      "Remove core from tomatoes and blend",
      "Add blended tomato, 1 tbsp garlic powder, 1 tbsp onion, 1/2 tbsp honey, 1 tsp chili flakes, and 1/2 tbsp oregano to pot and bring to boil",
      "Simmer for about an hour, until sauce looks like tomato sauce",
      "Mix ground beef, 2 tsp chili flakes, 1 tbsp garlic powder, 1 tbsp onion powder, 1/2 tbsp basil, 1/2 tbsp parsley, 2 tsp salt in a bowl by hand",
      "Create 1 inch balls",
      "Sear all sides in a large pan",
      "* Meatball temp: 145F",
      "* Save all leftover veggies in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Cheese Steak",
    image: "no image found",
    type: ["Main"],
    ingredients: [
      "1 lb Cheese steak meat",
      "American cheese",
      "Mayo",
      "Lettuce",
      "1 tomato",
      "1 red onion",
      "Roll",
      "italian seasoning",
    ],
    steps: [
      "* Save all leftover veggies in a 1 gal freezer bag for future broth",
    ],
  },
  {
    name: "Chocolate Chocolate Peanut Butter Chip Brownies",
    image: "no image found",
    type: ["Dessert"],
    ingredients: [
      "1 1/2 cup butter",
      "1 egg",
      "3/4 cup brown sugar",
      "1/4 cup granulated sugar",
      "1 tsp vanilla",
      "1 tbsp instant coffee",
      "2 tbsp milk",
      "3/4 cup flour",
      "1/3 cup cacao powder",
      "1 1/2 tsp baking soda",
      "1 tsp salt",
    ],
    steps: ["Set oven to 350F", "Mix all ingredients", "Bake 22-28 min"],
  },
  {
    name: "Adobo",
    image: "no image found",
    type: ["Sauce"],
    ingredients: [
      "3 tbsp salt",
      "3 tbsp garlic",
      "2 tsp black pepper",
      "1 tsp oregano",
      "1/2 tsp turmeric",
    ],
    steps: ["Mix all and store in an old spice container"],
  },
  {
    name: "Sazon",
    image: "no image found",
    type: ["Sauce"],
    ingredients: [
      "2 tbsp onion powder",
      "2 tbsp garlic powder",
      "2 tbsp salt",
      "1 tsp cumin",
      "2 1/2 tbsp Annatto/ achiote",
      "2 tbsp coriander",
    ],
    steps: ["Mix all and store in an old spice container"],
  },
  {
    name: "Creme Brulee Cheesecake(12)",
    image: "no image found",
    type: ["Dessert"],
    ingredients: [
      "9 graham crackers",
      "6 tbsp melted butter",
      "3/4 c granulated sugar",
      "16 oz softened cream cheese",
      "1 tsp vanilla",
      "1 egg",
      "2 egg yolks",
      "1/2 c sour cream",
      "1/4 tsp salt",
    ],
    steps: [
      "Set oven to 275F",
      "Smash graham crackers and put in bowl",
      "Mix the butter and 1/4 c sugar with graham crackers",
      "Line bottom of muffin tin with graham cracker crust",
      "In a large bowl mix cream cheese, 1/2 c sugar, vanilla, egg, egg yolks, sour cream, and salt",
      "Add to top of graham cracker crust",
      "Bake for 25 min",
    ],
  },
  {
    name: "Buffalo Chicken Dip",
    image: "no image found",
    type: ["Sauce", "Side"],
    ingredients: [
      "1 cans of shredded chicken",
      "8 oz cheddar cheese",
      "1/4 c hot sauce",
      "8 oz cream cheese",
      "1/8 c olive oil",
    ],
    steps: [
      "Add olive oil to heated pan",
      "Add canned chicken and stir until slightly browned",
      "Add hot sauce, cream cheese, and shredded cheese",
    ],
  },
  {
    name: "Mozzarella Sticks",
    image: "no image found",
    type: ["Side"],
    ingredients: [
      "8 oz mozzarella cheese",
      "2 c soft white flour",
      "2 tbsp salt",
      "1 tbsp onion powder",
      "1 tbsp garlic powder",
      "2 eggs",
      "1/3 c milk",
      "1 qt olive oil",
    ],
    steps: [
      "Cut mozzarella into 1/2 inch by 3 inch rectangular cubes",
      "Place on parchment paper and freeze for 45 min",
      "15 min before removing mozzarella from freezer heat oil in pot to 350F",
      "In a bowl mix the flour, salt, onion powder, and garlic powder",
      "In a smaller bowl mix milk, and eggs",
      "Remove mozzarella from freezer",
      "Dip mozzarella in egg, flour, egg, then flour again, and place on parchment paper",
      "Once all sticks are coated add to oil and fry for 90 sec/golden brown",
    ],
  },
  {
    name: "Protein Packed Chocolate Pudding",
    image: "no image found",
    type: ["Sauce"],
    ingredients: [
      "4 boiled eggs",
      "3 tbsp cacao powder",
      "1/2 c milk",
      "1/4 c honey",
    ],
    steps: [
      "Blend all until smooth",
      "Put in fridge to thicken or drink right away",
    ],
  },
  {
    name: "Pastelillos",
    image: "no image found",
    type: ["Main"],
    ingredients: [
      "1 lb ground beef",
      "Goya 10 pack orange disc",
      "2 tsp adobo",
      "2 packets sazon",
      "Cheese slices",
      "2 c olive oil",
    ],
    steps: [
      "Cook ground beef and drain oil",
      "Add sazon and adobo to ground beef",
      "Add beef mixture and half a slice of cheese to center of disc",
      "Fold disc over in half and use fork prongs to seal disc edges by pressing down",
      "Heat pan and fill with oil",
      "Add disc to pan",
      "Fry each side for 2 minutes while splashing oil on top of disc to create bubbles and even cooking",
    ],
  },
  {
    name: "Coquito",
    image: "no image found",
    type: ["Drink"],
    ingredients: [
      "1 condensed milk",
      "1 evaporated milk",
      "2 cream of coconut",
      "2 cups Bacardi rum",
      "1 tbsp Cinnamon",
      "1 tbsp Vanilla",
    ],
    steps: ["Mix all in a blender"],
  },
  {
    name: "Deep Fried Turkey",
    image: "no image found",
    type: ["Holiday_Thanksgiving", "Main"],
    ingredients: [
      "~20 lbs whole turkey",
      "3 gal peanut oil",
      "1 gal vegetable oil",
    ],
    steps: [
      "Put turkey in a bag in fridge 10 days before cooking",
      "Add turkey to giant pot and fill with water",
      "Take note of how much water was needed to then add the amount of oil",
      "Remove turkey from water and pat dry",
      "Heat oil to 400F in a large pot",
      "Fry turkey at 3 min per pound at 350F",
    ],
  },
  {
    name: "Pumpkin Roll",
    image: "no image found",
    type: ["Holiday_Thanksgiving", "Dessert"],
    ingredients: [
      "1 c granulated sugar",
      "3/4 c soft white flour",
      "1 tsp baking powder",
      "3 1/2 tsp pumpkin spice",
      "1/4 tsp salt",
      "3 eggs",
      "3/4 c pumpkin puree",
      "2 c + 2 tbsp powdered sugar",
      "16 oz cream cheese",
      "1/4 c + 2 tbsp butter",
      "2 tsp vanilla",
    ],
    steps: [
      "Preheat oven to 350F",
      "Place cream cheese and butter on stove until softened",
      "Cover a cookie sheet with side walls with parchment paper",
      "Mix the granulated sugar, flour, baking powder, 2 tsp pumpkin spice, and salt",
      "Mix in eggs and pumpkin puree",
      "Let mixture sit covered for 10 min",
      "pour evenly onto cookie sheet",
      "Bake for 15 minutes",
      "Dust 2 tbsp powdered sugar on a kitchen towel",
      "Place cake with parchment paper side up onto towel",
      "Roll short side of cake without removing the parchment paper",
      "let it completely cool",
      "In a small bowl mix cream cheese, 2 c powdered sugar, butter, vanilla, and 1 1/2 tsp pumpkin spice",
      "Unroll cooled cake and remove parchment paper",
      "Spread 1/2 the cream cheese mixture onto roll and store the other half in the fridge",
      "Roll the cake and place in fridge for 1 hr",
      "Cut into slices when ready and add extra cream cheese on top",
    ],
  },
  {
    name: "Turkey Sandwich(2)",
    image: "no image found",
    type: ["Main", "Holiday_Thanksgiving"],
    ingredients: [
      "3 tbsp mayo",
      "8 strips of bacon",
      "slices of fried turkey",
      "lettuce",
      "1 tomato",
      "red onion",
      "stone ground mustard",
      "multi grain sliced bread",
      "salt",
      "8 olives",
      "raw cheddar cheese",
    ],
    steps: [
      "Heat oven to 425F",
      "Cook bacon for 15 min/crispy",
      "Pour bacon grease into large pan",
      "Add turkey slices to pan with salt and cook 2 min each side",
      "Slice tomato, red onion, olives, and cheese",
      "Put mayo on both insides of sliced bread",
      "Layer cheese, turkey, bacon, cheese, red onion, olives, mustard, tomato, bacon, and lettuce",
    ],
  },
  {
    name: "Homemade Mayo",
    image: "no image found",
    type: ["Sauce"],
    ingredients: [
      "1 egg",
      "1/2 tsp salt",
      "1 tsp apple cider vinegar",
      "3/4 c avocado oil",
    ],
    steps: [
      "Add all ingredients to a small jar",
      "Blend with immersion blender",
      "* Store in fridge for 5 days",
    ],
  },
  {
    name: "Homemade Butter",
    image: "no image found",
    type: ["Sauce"],
    ingredients: [
      "1 pt heavy whipping cream",
      "1/2 tbsp salt",
      "1/2 c avocado oil",
    ],
    steps: [
      "Bring cream to room temp ( best to speed up process)",
      "Add cream to stand mixer",
      "Blend on high until butter separates from buttermilk",
      "Squeeze butter to form a ball",
      "Store buttermilk for other recipes",
      "Place butter back in stand mixer bowl and add salt",
      "Blend and slowly add avocado oil",
      "Pour into container and use right away or store in fridge",
    ],
  },
  {
    name: "Biscuits",
    image: "no image found",
    type: ["Holiday_Thanksgiving"],
    ingredients: ["2 cans pillsbury grand layer butter biscuits"],
    steps: ["Follow directions on can and use the shorter time"],
  },
  {
    name: "Cranberry Jelly",
    image: "no image found",
    type: ["Holiday_Thanksgiving"],
    ingredients: ["2 cans ocean spray cranberry jellied"],
    steps: ["Cut open can and slice"],
  },
  {
    name: "Garlic Mashed Potatoes",
    image: "no image found",
    type: ["Holiday_Thanksgiving", "Side"],
    ingredients: [
      "3 russet potatoes",
      "1 bulb of garlic",
      "1/4 c butter",
      "1/2 c milk",
      "2 tsp salt",
      "1 tbsp olive oil",
    ],
    steps: [
      "Chop potatoes into small cubes",
      "Bring water to boil and add potatoes",
      "Boil for 20 min and drain",
      "Add potatoes to large bowl and mash",
      "Heat oven to 400F",
      "Add chopped garlic to oven safe bowl and add olive oil",
      "Bake for 20 min",
      "Mix in garlic, butter, milk, and salt to potatoes",
    ],
  },
  {
    name: "Cornbread",
    image: "no image found",
    type: ["Holiday_Thanksgiving"],
    ingredients: ["1 box Fleischmann's Simply Homemade Corn Bread"],
    steps: ["Follow instructions on box"],
  },
  {
    name: "Fresh Corn",
    image: "no image found",
    type: ["Holiday_Thanksgiving"],
    ingredients: ["3 ears of corn"],
    steps: ["Husk and grill"],
  },
  {
    name: "Propane Tank",
    image: "no image found",
    type: ["Holiday_Thanksgiving"],
    ingredients: ["1 propane tank"],
    steps: ["Check if it needs to be refilled"],
  },
  // {
  //   name: "",
  //   image: "no image found",
  //   type: ["Main", "Breakfast", "Holiday_Thanksgiving", "Holiday_Christmas",
  // "Dessert", "Bakery", "Misc", "Drink", "Side", "Sauce", "Jam"],
  //   ingredients: [
  //   ],
  //   steps: [
  //   ],
  // },
]
