export const recipes = [
  {
    id: 1,
    name: "avocado_lime",
    image: "../images/avocado_lime.jpg",
    type: ["Sauce"],
    ingredients: [],
    steps: [],
  },
  {
    id: 2,
    name: "Bagel",
    image: "../images/bagels.jpg",
    type: ["Bakery"],
    ingredients: [
      "1/2 c soft white flour",
      "1/2 c hard white flour",
      "227g whole milk greek yogurt",
      "2 tsp baking powder",
      "1 tsp salt",
      "1 egg",
      "everything but the bagel seasoning"
    ],
    steps: [
      "Set oven to 400F",
      "In a bowl mix flour, baking powder, and salt",
      "Add yogurt and mix with fork",
      "Knead with oiled hands for 5 minutes",
      "Rest for 5 minutes",
      "Add oil to hands and create 3 bagel shapes with extra large holes",
      "In a small bowl mix egg and brush onto bagels",
      "Sprinkle Everything But the Bagel Seasoning",
      "Bake for 30 minutes"
    ],
  },
  {
    id: 3,
    name: "beef_bone_in_chuck_roast",
    image: "../images/beef_bone_in_chuck_roast.jpg",
    type: ["Main"],
    ingredients: [],
    steps: [],
  },
  {
    id: 4,
    name: "beef_sirloin_tip_roast",
    image: "../images/beef_sirloin_tip_roast.jpg",
    type: ["Main"],
    ingredients: [],
    steps: [],
  },
  {
    id: 5,
    name: "bone_broth",
    image: "../images/bone_broth.jpg",
    type: ["Sauce"],
    ingredients: [],
    steps: [],
  },
  {
    id: 6,
    name: "boneless_ribs",
    image: "../images/boneless_ribs.jpg",
    type: ["Main", "Sauce"],
    ingredients: [],
    steps: [],
  },
  {
    id: 7,
    name: "bread_loaf",
    image: "../images/bread_loaf.jpg",
    type: ["Bakery"],
    ingredients: [],
    steps: [],
  },
  {
    id: 8,
    name: "buttermilk_pancakes",
    image: "src/images/buttermilk_pancakes.jpg",
    type: ["Breakfast"],
    ingredients: [],
    steps: [],
  },
  {
    id: 9,
    name: "cabbage_and_meatball",
    image: "../images/cabbage_and_meatball.jpg",
    type: ["Main"],
    ingredients: [],
    steps: [],
  },
  {
    id: 10,
    name: "carrot_cake",
    image: "../images/carrot_cake.jpg",
    type: ["Dessert"],
    ingredients: [],
    steps: [],
  },
  {
    id: 11,
    name: "cauliflower_shrimp",
    image: "../images/cauliflower_shrimp.jpg",
    type: ["Main"],
    ingredients: [],
    steps: [],
  },
  {
    id: 12,
    name: "cheese_burgers",
    image: "../images/cheese_burgers.jpg",
    type: ["Main"],
    ingredients: [],
    steps: [],
  },
  {
    id: 13,
    name: "cherry_pie",
    image: "../images/cherry_pie.jpg",
    type: ["Dessert", "Holiday_Thanksgiving"],
    ingredients: [],
    steps: [],
  },
  {
    id: 14,
    name: "chicken_garlic_aioli_tacos",
    image: "../images/chicken_garlic_aioli_tacos.jpg",
    type: ["Main", "Sauce"],
    ingredients: [],
    steps: [],
  },
  {
    id: 15,
    name: "Chicken Nugs and French Fries",
    image: "../images/chicken_nugs_and_french_fries.jpg",
    type: ["Side", "Main"],
    ingredients: [
      "olive oil",
      "chicken breast",
      "2 brown potatoes",
      "2 c white flour",
      "1/2 tbsp salt",
      "1/2 tbsp onion powder",
      "1/2 tbsp garlic powder",
      "1 egg",
      "1/4 c milk",
    ],
    steps: [
      "In blender add raw chicken and 1 uncooked potato",
      "Create nugget shapes and put in freezer for 30 minutes",
      "Chop potato into fry, rinse in water, then pat dry",
      "Mix egg and milk in small bowl",
      "In another bowl mix flour, salt, onion, and garlic",
      "Remove nuggets from freezer and dip into milk mixture then flour mixture",
      "Heat a pan, add enough oil to fry frys for 20 minutes",
      "Heat another pan with enough oil to fry nuggets for 20 minutes",
    ],
  },
  {
    id: 16,
    name: "Chicken Pot Pie",
    image: "../images/chicken_pot_pie.jpg",
    type: ["Main"],
    ingredients: [
      "pie crust recipe",
      "2 chicken breasts",
      "1 carrot",
      "1 cellery",
      "1/2 c peas",
      "2 brown potatoes",
      "1 tbsp thyme",
      "1/2 c yellow onion",
      "2 c chicken broth",
      "4 tbsp flour",
      "1/2 c half and half",
      "pinch of nutmeg",
      "4 tbsp butter",
      "salt",
      "pepper",
    ],
    steps: [
      "Make pie crust and prepare 2 dishes for filling",
      "Bake chicken breast in oven at 350F for 25 minutes",
      "Remove chicken and set oven to 400F",
      "Chop chicken into cubes",
      "Add broth, potatoes, carrots, onion, celery, carrot, and peas to pot",
      "Once pot is boiling put it to simmer for 10 minutes",
      "In a seperate pan melt butter and mix in flour until golden brown for roux",
      "Add half and half, nutmeg, thyme, salt, pepper to roux until pastey",
      "Add roux to broth",
      "Bake for 45 minutes",
    ],
  },
  {
    id: 17,
    name: "chipotle",
    image: "../images/chipotle.jpg",
    type: ["Main", "Sauce"],
    ingredients: [],
    steps: [],
  },
  {
    id: 18,
    name: "chocolate_candy",
    image: "../images/chocolate_candy.jpg",
    type: ["Dessert"],
    ingredients: [],
    steps: [],
  },
  {
    id: 19,
    name: "Chocolate Chocolate Peanut Butter Chip Cookies",
    image: "../images/chocolate_cookies.jpg",
    type: ["Dessert"],
    ingredients: [
      "1 egg",
      "1 c flour",
      "1 tsp baking soda",
      "3/4 c brown sugar",
      "1/3 c cacao powder",
      "1/4 c granulated sugar",
      "1 tsp salt",
      "1/2 c chocolate chips",
      "1/2 c peanut butter chips",
      "1 tsp vanilla",
      "1 tbsp instant coffee",
      "1/2 c butter",
    ],
    steps: ["From frozen: Preheat oven to 375F", "Bake for 8 1/2 minutes"],
  },
  {
    id: 20,
    name: "chocplate_rice_krispies",
    image: "../images/chocplate_rice_krispies.jpg",
    type: ["Dessert"],
    ingredients: [],
    steps: [],
  },
  {
    id: 21,
    name: "chulettas_and_platanos",
    image: "../images/chulettas_and_platanos.jpg",
    type: ["Side", "Main"],
    ingredients: [],
    steps: [],
  },
  {
    id: 22,
    name: "dippy_eggs",
    image: "../images/dippy_eggs.jpg",
    type: ["Breakfast"],
    ingredients: [],
    steps: [],
  },
  {
    id: 23,
    name: "dutch_oven_beff_stew",
    image: "../images/dutch_oven_beff_stew.jpg",
    type: ["Main"],
    ingredients: [],
    steps: [],
  },
  {
    id: 24,
    name: "english_muffins",
    image: "../images/english_muffins.jpg",
    type: ["Bakery"],
    ingredients: [],
    steps: [],
  },
  {
    id: 25,
    name: "fathers_day_special",
    image: "../images/fathers_day_special.jpg",
    type: ["Main"],
    ingredients: [],
    steps: [],
  },
  {
    id: 26,
    name: "flour_tortilla",
    image: "../images/flour_tortilla.jpg",
    type: ["Side", "Pre-requisite"],
    ingredients: [],
    steps: [],
  },
  {
    id: 27,
    name: "french_toast",
    image: "../images/french_toast.jpg",
    type: ["Breakfast"],
    ingredients: [],
    steps: [],
  },
  {
    id: 28,
    name: "grape_jelly",
    image: "../images/grape_jelly.jpg",
    type: ["Jam"],
    ingredients: [],
    steps: [],
  },
  { id: 29, name: "kabobs", image: "../images/kabobs.jpg", type: ["Main"] },
  {
    id: 30,
    name: "lemon_chicken_mushroom",
    image: "../images/lemon_chicken_mushroom.jpg",
    type: ["Main"],
    ingredients: [],
    steps: [],
  },
  { id: 31, name: "lotion", image: "../images/lotion.jpg", type: ["Misc"] },
  {
    id: 32,
    name: "mac_and_cheese_cicd",
    image: "../images/mac_and_cheese_cicd.jpg",
    type: ["Main", "Holiday_Thanksgiving"],
    ingredients: [],
    steps: [],
  },
  {
    id: 33,
    name: "mac_and_cheese_og",
    image: "../images/mac_and_cheese_og.jpg",
    type: ["Main", "Holiday_Thanksgiving"],
    ingredients: [],
    steps: [],
  },
  {
    id: 34,
    name: "Shrimp Mofongo 3 Ways",
    image: "../images/mofongo.jpg",
    type: ["Side", "Main", "Pre-requisite"],
    ingredients: [
      "4 platanos",
      "1 lb shrimp",
      "2 garlic bulbs",
      "olive oil",
      "avocado oil",
      "butter",
    ],
    steps: [
      "1/3 garlic in a glass dish in oil, roast in oven at 350F for 20 minutes",
      "1/3 garlic pan roast in butter",
      "1/3 garlic raw",
      "Chop platanos into 1 inch cubes",
      "Deep fry in olive oil until golden brown",
      "Place platanos in a bowl and set aside",
      "Cook shrimp and drain water",
      "Add pan roasted garlic to shrimp",
      "Mash platanos (add avocado oil if too dry)",
      "Add all to bowl",
    ],
  },
  { id: 35, name: "paella", image: "../images/paella.jpg", type: ["Main"] },
  {
    id: 36,
    name: "peach_jelly",
    image: "../images/peach_jelly.jpg",
    type: ["Jam"],
    ingredients: [],
    steps: [],
  },
  {
    id: 37,
    name: "peanut_butter_oats",
    image: "../images/peanut_butter_oats.jpg",
    type: ["Dessert"],
    ingredients: [],
    steps: [],
  },
  {
    id: 38,
    name: "pernil",
    image: "../images/pernil.jpg",
    type: ["Main", "Holiday_Christmas"],
    ingredients: [],
    steps: [],
  },
  {
    id: 39,
    name: "pie_crust",
    image: "../images/pie_crust.jpg",
    type: ["Bakery"],
    ingredients: [],
    steps: [],
  },
  {
    id: 40,
    name: "pizza_crust",
    image: "../images/pizza_crust.jpg",
    type: ["Bakery"],
    ingredients: [],
    steps: [],
  },
  {
    id: 41,
    name: "platanos_garlic",
    image: "../images/platanos_garlic.jpg",
    type: ["Main", "Sauce"],
    ingredients: [],
    steps: [],
  },
  {
    id: 41,
    name: "pollo_guisado",
    image: "../images/pollo_guisado.jpg",
    type: ["Main"],
    ingredients: [],
    steps: [],
  },
  {
    id: 42,
    name: "rostiaire_chicken",
    image: "../images/rostiaire_chicken.jpg",
    type: ["Main"],
    ingredients: [],
    steps: [],
  },
  { id: 43, name: "salmon", image: "../images/salmon.jpg", type: ["Main"] },
  {
    id: 44,
    name: "sausage_subs",
    image: "../images/sausage_subs.jpg",
    type: ["Main"],
    ingredients: [],
    steps: [],
  },
  {
    id: 45,
    name: "shawns_chili",
    image: "../images/shawns_chili.jpg",
    type: ["Main"],
    ingredients: [],
    steps: [],
  },
  {
    id: 46,
    name: "shawns_lemonade",
    image: "../images/shawns_lemonade.jpg",
    type: ["Drink"],
    ingredients: [],
    steps: [],
  },
  {
    id: 47,
    name: "shawns_tea",
    image: "../images/shawns_tea.jpg",
    type: ["Drink"],
    ingredients: [],
    steps: [],
  },
  {
    id: 48,
    name: "shepherds_pie",
    image: "../images/shepherds_pie.jpg",
    type: ["Main"],
    ingredients: [],
    steps: [],
  },
  {
    id: 49,
    name: "Shoulder Roast",
    image: "../images/shoulder_roast.jpg",
    type: ["Main"],
    ingredients: [
      "3 pieces of frozen beef bones",
      "4 c of water",
      "2 tbsp onion powder",
      "1 tbsp salt",
      "1/2 tbsp thyme",
      "1/2 tbsp smoked paprika",
      "4 lb shoulder roast",
    ],
    steps: [
      "Bake bones in oven at 350F for 1 hr",
      "Remove bones from oven and set oven to 275F",
      "Add bones, bone drippings, and water to boil for 30 minutes",
      "Add all spices to pot",
      "Stab roast with fork and add to pot",
      "Bake for 30 minutes, flip roast, and finish baking for 30 miutes",
    ],
  },
  {
    id: 50,
    name: "spaghetti_and_meatballs",
    image: "../images/spaghetti_and_meatballs.jpg",
    type: ["Main", "Pre-requisite"],
    ingredients: [],
    steps: [],
  },
  {
    id: 51,
    name: "spaghetti",
    image: "../images/spaghetti.jpg",
    type: ["Pre-requisite"],
    ingredients: [],
    steps: [],
  },
  {
    id: 52,
    name: "spanish_rice",
    image: "../images/spanish_rice.jpg",
    type: ["Side"],
    ingredients: [],
    steps: [],
  },
  {
    id: 53,
    name: "steak_poatato",
    image: "../images/steak_poatato.jpg",
    type: ["Main"],
    ingredients: [],
    steps: [],
  },
  {
    id: 54,
    name: "stir_fry",
    image: "../images/stir_fry.jpg",
    type: ["Pre-requisite"],
    ingredients: [],
    steps: [],
  },
  {
    id: 55,
    name: "stove_cleaner",
    image: "../images/stove_cleaner.jpg",
    type: ["Misc"],
    ingredients: [],
    steps: [],
  },
  {
    id: 56,
    name: "strawberry_jam",
    image: "../images/strawberry_jam.jpg",
    type: ["Jam"],
    ingredients: [],
    steps: [],
  },
  {
    id: 57,
    name: "stuffed_cabbage",
    image: "../images/stuffed_cabbage.jpg",
    type: ["Main"],
    ingredients: [],
    steps: [],
  },
  {
    id: 58,
    name: "stuffed_chicken",
    image: "../images/stuffed_chicken.jpg",
    type: ["Main"],
    ingredients: [],
    steps: [],
  },
  { id: 59, name: "sushi", image: "../images/sushi.jpg", type: ["Main"] },
  {
    id: 60,
    name: "sweet_potato_casserole",
    image: "../images/sweet_potato_casserole.jpg",
    type: ["Holiday_Thanksgiving"],
    ingredients: [],
    steps: [],
  },
  {
    id: 61,
    name: "thanksgiving_utensils",
    image: "../images/thanksgiving_utensils.jpg",
    type: ["Holiday_Thanksgiving"],
    ingredients: [],
    steps: [],
  },
  {
    id: 62,
    name: "tomato_sauce",
    image: "../images/tomato_sauce.jpg",
    type: ["Sauce"],
    ingredients: [],
    steps: [],
  },
  {
    id: 63,
    name: "top_round",
    image: "../images/top_round.jpg",
    type: ["Main"],
    ingredients: [],
    steps: [],
  },
  {
    id: 64,
    name: "tortilla_chips",
    image: "../images/tortilla_chips.jpg",
    type: ["Side", "Pre-requisite"],
    ingredients: [],
    steps: [],
  },
  {
    id: 65,
    name: "waffles_pancakes",
    image: "../images/waffles_pancakes.jpg",
    type: ["Breakfast"],
    ingredients: [],
    steps: [],
  },
  {
    id: 66,
    name: "zuchini_bread",
    image: "../images/zuchini_bread.jpg",
    type: ["Dessert"],
    ingredients: [],
    steps: [],
  },
  {
    id: 67,
    name: "taco_dip",
    image: "Errr...loading...taco_dip",
    type: ["Main"],
    ingredients: [],
    steps: [],
  },
]
