export const recipes = [
  {
    name: "Avocado Lime",
    image: "../images/avocado_lime.jpg",
    type: ["Sauce"],
    ingredients: [
      "3 tbsp lime juice",
      "2 avocados",
      "1 c cashews",
      "2 tbsp avocado oil",
      "1 c spinash",
      "1 tsp salt",
    ],
    steps: ["Add all ingredients to blender"],
  },
  {
    name: "Bagel(3)",
    image: "../images/bagels.jpg",
    type: ["Bakery"],
    ingredients: [
      "1/2 c soft white flour",
      "1/2 c hard white flour",
      "227g whole milk greek yogurt",
      "2 tsp baking powder",
      "1 tsp salt",
      "1 egg",
      "everything but the bagel seasoning",
    ],
    steps: [
      "Set oven to 400F",
      "In a bowl mix flour, baking powder, and salt",
      "Add yogurt and mix with fork",
      "Knead with oiled hands for 5 minutes",
      "Rest for 5 minutes",
      "Add oil to hands and create 3 bagel shapes with extra large holes",
      "In a small bowl mix egg and brush onto bagels",
      "Sprinkle Everything But the Bagel Seasoning",
      "Bake for 30 minutes",
    ],
  },
  {
    name: "Beef Bone in Chuck Roast",
    image: "../images/beef_bone_in_chuck_roast.jpg",
    type: ["Main"],
    ingredients: [
      "4 lb chuck roast",
      "3 tbsp olive oil",
      "1 tbsp onion powder",
      "1 tbsp garlic powder",
      "1 tbsp thyme",
      "1 tbsp salt",
      "1 tbsp pepper",
      "1 tsp red chili flakes",
      "1 tsp smoked paprika",
    ],
    steps: [
      "In a small bowl mix onion, garlic, thyme, salt, pepper, chili flakes, and smoked paprika",
      "Add seasoning all over roast and marindade for at least 1 hr in the fridge",
      "Take roast out of fridge 1 hr before cooking",
      "Set oven to 275F",
      "In dutch oven add olive oil and sear all sides of roast",
      "Bake for 10 minutes/lb",
      "* Roast temp: 145F",
    ],
  },
  {
    name: "Beef Sirloin Tip Roast",
    image: "../images/beef_sirloin_tip_roast.jpg",
    type: ["Main"],
    ingredients: [
      "4 lb beef sirloin tip roast",
      "olive oil",
      "salt",
      "pepper",
      "Bone broth recipe (2 c broth per 2 lbs of meat",
      "1 tbsp onion powder",
      "1 tbsp gralic powder",
      "1 tsp smoked paprika",
    ],
    steps: [
      "Make bone broth recipe",
      "Set oven to 400F",
      "Salt and pepper each side of the roasr",
      "In dutch oven heat with olive oil and sear each side of roast",
      "Add broth, onion, garlic, and smoked paprika",
      "Bake for 15 min and set oven to 300F",
      "Bake for 45 minutes per 2 lbs of meat",
      "Shred while still in pot",
    ],
  },
  {
    name: "Bone Broth",
    image: "../images/bone_broth.jpg",
    type: ["Sauce"],
    ingredients: ["2 lbs frozen beef bones", "1 gal of water", "2 tbsp salt"],
    steps: [
      "Bake bones in oven at 400F for 1 hr",
      "Add bones, bone drippings, salt, and water to pot",
      "Boil then simmer for 4 hrs",
    ],
  },
  {
    name: "Boneless Rib",
    image: "../images/boneless_ribs.jpg",
    type: ["Main"],
    ingredients: [
      "1 lb of any meat",
      "Brocolli",
      "2 tbsp honey",
      "1 1/2 tsp chili flakes",
      "1 tsp smoked paprika",
      "1 1/2 tsp salt",
      "2 tbsp olive oil",
    ],
    steps: [
      "Thinly slice meat and put in a bowl",
      "To bowl add honey, chili flakes, smoked paprika, salt, and olive oil",
      "Marinade for 1 hour",
      "Remove meat 30 minutes before cooking",
      "Chop brocolli",
      "Cook meat in pan and add brocolli",
      "Set flame high to burn off extra liquid",
    ],
  },
  {
    name: "Bread Loaf",
    image: "../images/bread_loaf.jpg",
    type: ["Bakery"],
    ingredients: [
      "1 tbsp yeast",
      "1 1/2 c 115F water",
      "3 1/2 c soft white flour",
      "1/2 c hard white flour",
      "1/4 c olive oil",
      "1/4 c honey",
      "2 tsp salt",
    ],
    steps: [
      "Mix yeast and water in a bowl",
      "STir until yeast is dissolved",
      "Add 1 1/2 c soft white flour and mix",
      "Cover and rest for 20 minutes or until bubbly",
      "Add remainging soft white flour, honey, oil, and salt",
      "Knead in stand mixer until dough ball forms, about 5 minutes",
      "If dough is sticking to sides slowly add hard white flour a small amount at a time",
      "Flour counter and shape dough into a long rectangle",
      "Fold into thirds then roll the long way and pinch the ends under",
      "Place in parchment paper before putting in bread pan",
      "Let rest for 1 hour or until the height of the bread pan",
      "Heat oven to 350F and bake for 40 minutes",
      "Let cool before slicing",
    ],
  },
  {
    name: "Cabbage and Meatball",
    image: "../images/cabbage_and_meatball.jpg",
    type: ["Main"],
    ingredients: [
      "1 cabbage",
      "1 lb ground beef",
      "8 red potatoes",
      "8 tomatoes",
      "1 bulb of garlic",
      "2 tbsp salt",
      "Veggie broth recipe",
    ],
    steps: [
      "Make veggie broth recipe",
      "Chop cabbage into quarters",
      "Chop potatoes in half",
      "Remove top core of tomatoes",
      "Chop ends of garlic",
      "Make 1 inch meatballs",
      "Add all to giant pot and simmer for 2 hours",
    ],
  },
  {
    name: "Carrot Cake",
    image: "../images/carrot_cake.jpg",
    type: ["Dessert"],
    ingredients: [
      "3 c shredded carrots",
      "1/2 tsp ginger",
      "2 eggs",
      "1 tsp baking powder",
      "1/2 tsp baking soda",
      "6 tbsp agave",
      "1 tsp cinnamon",
      "1/4 tsp cloves",
      "1/4 tsp nutmeg",
      "1/2 tsp salt",
      "3 tsp vanilla",
      "1/2 c olive oil",
      "1 c hard red flour",
    ],
    steps: ["Mix all together", "Bake at 350F for 50 min"],
  },
  {
    name: "Cauliflower Shrimp",
    image: "../images/cauliflower_shrimp.jpg",
    type: ["Main"],
    ingredients: [
      "1 head of cauliflower",
      "1 lb shrimp",
      "1/2 green pepper",
      "1/2 yellow onion",
      "1 garlic bulb",
      "shelled edamame",
      "2 tsp onion powder",
      "2 tsp garlic powder",
      "1 tsp salt",
      "1 tsp basil",
    ],
    steps: [
      "Chop cauliflower, green pepper, onion, and garlic",
      "Cook pepper and onion until lightly browned",
      "Add all ingredients to pan and cook until shrimp is pink",
    ],
  },
  {
    name: "Fried Tacos",
    image: "no image found",
    type: ["Main"],
    ingredients: [
      "Masa recipe",
      "1 lb ground beef",
      "Guacamole recipe",
      "8 oz block of pepper jack cheese",
      "Lettuce",
      "Olive oil",
    ],
    steps: [
      "Masa recipe but stop after forming into balls",
      "Heat oil to 325F in a flat bottom pan",
      "Flatten masa ball and fry one side for 1 minute and the other for 50 sec",
      "Fold in half and set aside to cool",
    ],
  },

  {
    name: "Masa Tacos",
    image: "no image found",
    type: ["Main"],
    ingredients: ["2 tsp salt", "1 2/3 cup 100F water", "2 1/2 c masa harina"],
    steps: [
      "Mix all together with a fork in a bowl",
      "Knead until smooth",
      "Form 12 1 1/2 inch balls",
      "Rest for at least 30 minutes",
      "Heat electric griddle on high",
      "Flatten each ball and cook for 2 minutes each side",
    ],
  },
  {
    name: "Cheese Burgers",
    image: "../images/cheese_burgers.jpg",
    type: ["Main"],
    ingredients: [
      "Homemade Bread Recipe or store bought",
      "1 lb ground beef or patties",
      "cheese",
      "red onion",
      "1 tomato",
      "lettuce",
      "ketchup",
      "mayo",
      "spicy brown mustard",
      "bacon",
    ],
    steps: [
      "Make burger buns",
      "Bake bacon in oven 425F for 15 minutes",
      "Form burger patties and cook/grill",
      "Stack it",
      "* burger temp: 185F",
    ],
  },
  {
    name: "Thanksgiving Items",
    image: "../images/cherry_pie.jpg",
    type: ["Misc", "Holiday_Thanksgiving"],
    ingredients: ["Brown paper bags", "Aluminum pan"],
    steps: [],
  },
  {
    name: "Cherry Pie",
    image: "../images/cherry_pie.jpg",
    type: ["Dessert", "Holiday_Thanksgiving"],
    ingredients: [
      "Pie crust recipe",
      "3 cans Oregan red tart cherries",
      "1 tbsp lemon",
      "1/4 tsp almond extract",
      "2/3 c agave",
      "3/4 c brown sugar",
      "2 tbsp cinnamon",
    ],
    steps: [
      "Make pie crust recipe",
      "In a shallow pan add 1 1/2 cans of cherry juice, all the cherries, lemon, almond extract, and agave",
      "Cook in medium heat until it starts to thicken",
      "Set oven to 375F and bake for 15 min",
      "Mix the sugar and cinnamon and pour over pie",
      "Bake for another 5 min",
    ],
  },
  {
    name: "Chicken Garlic Aioli Tacos",
    image: "../images/chicken_garlic_aioli_tacos.jpg",
    type: ["Main", "Sauce"],
    ingredients: [
      "Masa recipe",
      "Garlic aioli recipe",
      "2 chicken breast",
      "5 tbsp mayo",
      "1 tbsp basil",
      "2 garlic bulbs",
      "2 tomatoes",
    ],
    steps: [
      "Make masa recipe",
      "Make garlic aioli recipe",
      "Cut chicken into strips and cook in pan",
      "* Chicken temp: 165F",
    ],
  },
  {
    name: "Garlic Aioli",
    image: "../images/chicken_garlic_aioli_tacos.jpg",
    type: ["Sauce"],
    ingredients: [
      "5 tbsp mayo",
      "1 tbsp basil",
      "2 garlic bulbs",
      "2 tomatoes",
    ],
    steps: [
      "Chop garlic",
      "Chop tomatoes",
      "Add all to a bowl and mix",
      "Let sit for at least 15 minutes",
    ],
  },
  {
    name: "Chicken Nugs and French Fries",
    image: "../images/chicken_nugs_and_french_fries.jpg",
    type: ["Side", "Main"],
    ingredients: [
      "olive oil",
      "chicken breast",
      "2 brown potatoes",
      "2 c white flour",
      "1/2 tbsp salt",
      "1/2 tbsp onion powder",
      "1/2 tbsp garlic powder",
      "1 egg",
      "1/4 c milk",
    ],
    steps: [
      "In blender add raw chicken and 1 uncooked potato",
      "Create nugget shapes and put in freezer for 30 minutes",
      "Chop potato into fry, rinse in water, then pat dry",
      "Mix egg and milk in small bowl",
      "In another bowl mix flour, salt, onion, and garlic",
      "Remove nuggets from freezer and dip into milk mixture then flour mixture",
      "Heat a pan, add enough oil to fry frys for 20 minutes",
      "Heat another pan with enough oil to fry nuggets for 20 minutes",
    ],
  },
  {
    name: "Chicken Pot Pie",
    image: "../images/chicken_pot_pie.jpg",
    type: ["Main"],
    ingredients: [
      "pie crust recipe",
      "2 chicken breasts",
      "1 carrot",
      "1 cellery",
      "1/2 c peas",
      "2 brown potatoes",
      "1 tbsp thyme",
      "1/2 c yellow onion",
      "2 c chicken broth",
      "4 tbsp flour",
      "1/2 c half and half",
      "pinch of nutmeg",
      "4 tbsp butter",
      "salt",
      "pepper",
    ],
    steps: [
      "Make pie crust and prepare 2 dishes for filling",
      "Bake chicken breast in oven at 350F for 25 minutes",
      "Remove chicken and set oven to 400F",
      "Chop chicken into cubes",
      "Add broth, potatoes, carrots, onion, celery, carrot, and peas to pot",
      "Once pot is boiling put it to simmer for 10 minutes",
      "In a seperate pan melt butter and mix in flour until golden brown for roux",
      "Add half and half, nutmeg, thyme, salt, pepper to roux until pastey",
      "Add roux to broth",
      "Bake for 45 minutes",
    ],
  },
  {
    name: "Guacamole",
    image: "../images/guacamole.jpg",
    type: ["Side"],
    ingredients: [
      "1 bunch of cilantro",
      "1 lime",
      "3 avocados",
      "1 tomato",
      "1/4 c red onion",
    ],
    steps: [
      "Slice avocados and mash in a bowl",
      "Roll lime, slice in half and squeeze juice into bowl",
      "Chop red onion, tomato, and 1/2 bunch of cilanto and add to bowl",
    ],
  },
  {
    name: "Chipotle",
    image: "../images/chipotle.jpg",
    type: ["Main"],
    ingredients: [
      "1 lb steak",
      "white rice recipe",
      "black beans recipe",
      "guacamole recipe",
      "1 yellow onion",
      "1 green pepper",
      "1/4 c olive oil",
      "1 corn",
    ],
    steps: [
      "Make white rice recipe",
      "Make black beans recipe",
      "Make guacamole recipe",
      "Heat pan with oil",
      "Chop peppers add to pan until soft",
      "Add half sliced onions to pan",
      "Once you see char on ppers and onions add sliced corn kernels",
      "Turn off heat once corn gets a char",
      "Make steak recipe",
    ],
  },
  {
    name: "Chocolate Candy",
    image: "../images/chocolate_candy.jpg",
    type: ["Dessert"],
    ingredients: [
      "1/3 c honey/maple syrup",
      "3/4 c cacao",
      "1/8 tsp salt",
      "1 tsp vanilla",
      "3/4 c coconut oil",
    ],
    steps: [
      "In a pan, on ow heat, add all ingredients on low heat",
      "Once all well mixed, pour into mold and cool in fridge",
    ],
  },
  {
    name: "Chocolate Chocolate Peanut Butter Chip Cookies",
    image: "../images/chocolate_cookies.jpg",
    type: ["Dessert"],
    ingredients: [
      "1 egg",
      "1 c flour",
      "1 tsp baking soda",
      "3/4 c brown sugar",
      "1/3 c cacao powder",
      "1/4 c granulated sugar",
      "1 tsp salt",
      "1/2 c chocolate chips",
      "1/2 c peanut butter chips",
      "1 tsp vanilla",
      "1 tbsp instant coffee",
      "1/2 c butter",
    ],
    steps: [
      "Mix all the dry ingredients then add all the wet ingredients",
      "Add to freezer bag and flatten",
      "with a butter knife indent a 6 x 4 grid and place bag in freezer",
      "From frozen: Preheat oven to 375F",
      "Bake for 8 1/2 minutes",
    ],
  },
  {
    name: "Chocolate Rice Krispies",
    image: "../images/chocolate_rice_krispies.jpg",
    type: ["Dessert"],
    ingredients: [
      "1 bag mini marshmallows",
      "6 tbsp butter",
      "4 oz chocolate bar",
      "6 c rice krispies",
      "1/4 c cacao",
    ],
    steps: [
      "Add butter and marshamallow to flat bottom pan",
      "Mix in the rice krispies and cacao and cook on low heat",
      "Put in a glass pan, squish down, and cool",
      "Melt chocolate bar and drizzle over rice krispies",
    ],
  },
  {
    name: "Chuletas and Tostones",
    image: "../images/chuletas_and_tostones.jpg",
    type: ["Side", "Main"],
    ingredients: [
      "tostones recipe",
      "garlic recipe",
      "3 chuletas",
      "salt",
      "oil of choice: butter, tallow, ghee",
    ],
    steps: [
      "Make tostones recipe",
      "Make garlic recipe",
      "Set oven to 450F",
      "Fry chuletas in oil and salt for 3 minutes",
      "Flip and bake for 3 minutes",
      "* chuleta temp: 145F",
    ],
  },
  {
    name: "Dippy Eggs",
    image: "../images/dippy_eggs.jpg",
    type: ["Breakfast"],
    ingredients: ["sliced bread", "eggs", "salt", "butter"],
    steps: ["toast bread and add butter", "fry eggs in butter and add salt"],
  },
  {
    name: "Dutch Oven Beef Stew",
    image: "../images/dutch_oven_beef_stew.jpg",
    type: ["Main"],
    ingredients: [
      "2 lb beef stew meat",
      "1 1/2 tbsp garlic powder",
      "2 tsp onion powder",
      "1 tsp chili powder",
      "1/8 tsp smoked paprika",
      "1 tsp salt",
      "1/4 tsp black pepper",
      "1/4 tsp cinnamon",
      "3 tbsp honey",
      "3 brown potatoes",
      "1 yellow onion",
      "2 carrots",
      "4 celery stalks",
      "2 c veggie broth recipe",
    ],
    steps: [
      "Make veggie broth recipe",
      "Mix dry ingredients and pat on the sides of the beef",
      "Drizzle honey on both sides",
      "Marinade until ready to cook",
      "Set oven to 350F",
      "Sear all sides of beef in dutch oven then set aside",
      "Add 1 c of broth to remove burnt pieces on bottom of dutch oven",
      "Add the beef and add the veggies around",
      "Add 1 c of broth",
      "Put in oven for 20 minutes per lb",
      "Remove from oven and add potatoes and enough broth to cover",
      "Put back in oven for 20 minutes",
      "* Beef temp: 145F",
    ],
  },
  {
    name: "Veggie Broth",
    image: "no image found",
    type: ["Sauce"],
    ingredients: ["Bag of frozen veggies", "2 tbsp salt", "3 qrts Water"],
    steps: [
      "Place all in pot and boil for at least 2 hrs",
      "Strain and save broth",
    ],
  },
  {
    name: "English Muffins(CICD)",
    image: "../images/english_muffins.jpg",
    type: ["Bakery"],
    ingredients: [
      "1 c soft white flour",
      "227g whole milk greek yogurt",
      "2 tsp baking powder",
      "1 tsp salt",
      "1 tsp sugar",
    ],
    steps: [
      "Set oven to 400F",
      "In a bowl mix flour, baking powder, sugar, and salt",
      "Add yogurt and mix with fork",
      "Knead with oiled hands for 5 minutes",
      "Rest for 5 minutes",
      "Add oil to hands and create 3 english muffin shapes",
      "Add butter to pan and placemuffins in pan",
      "Cook one side for 7 minutes and the other side for 5 minutes",
    ],
  },
  {
    name: "Fathers Day Special",
    image: "../images/fathers_day_special.jpg",
    type: ["Main"],
    ingredients: [
      "~2lb live lobster",
      "Ghee or 1 stick of butter",
      "1 lb clams",
      "1 lb crab legs",
    ],
    steps: [
      "Bring water to a boil in a pot large enought o fit the whole lobster",
      "Heat oven to 425F",
      "Bake frozen crab legs for 15 minutes",
      "Heat oven to 475F and add clams for 15 minutes",
      "Add lobster to boiling water",
      "Once water begins to boil again leave lobster in for 10 minutes for the 1st lb and 3 minutes for every lb after",
      "Melt butter on low heat",
      "Turn off the heat and remove the top foam",
      "Slowly pour the clear part of the melted butter into a bowl",
    ],
  },
  {
    name: "Flour Tortilla",
    image: "../images/flour_tortilla.jpg",
    type: ["Side", "Pre-requisite"],
    ingredients: [
      "2 c white flour",
      "3/4 c water",
      "3 tbsp avocado oil",
      "1/2 tsp salt",
    ],
    steps: [
      "Heat water to 110F",
      "In a bowl mix, flour, water, oil, and salt until it looks like a rough dough ball",
      "Rest for 5 minutes",
      "Flour counter and knead dough until smooth",
      "Rest for 5 minutes",
      "Make 1 1/2 inch balls",
      "Heat griddle on max",
      "Flatten dough ball and place on griddle for 30 seconds each side",
    ],
  },
  {
    name: "French Toast",
    image: "../images/french_toast.jpg",
    type: ["Breakfast"],
    ingredients: [
      "sliced bread",
      "1 egg/2 slices of bread",
      "1/4 c milk/1 egg",
    ],
    steps: ["Mix egg and milk in a bowl", "Dip bread in egg dip"],
  },
  {
    name: "Grape Jelly",
    image: "../images/grape_jelly.jpg",
    type: ["Jam"],
    ingredients: [
      "1 lb black or red seedless grapes",
      "3 tbsp lemon juice",
      "2/3 c agave",
      "1 mason jar for storage",
    ],
    steps: [
      "Blend grapes",
      "Set oven to 200F",
      "Add grapes, lemon, and agave to a pot on medium heat",
      "Turn off stove and place jar in oven for 20 mimutes",
      "Boil grapes while stirring every 10 minutes until thickened about 30 minutes",
      "Place in jar, seal, and let cool",
    ],
  },
  {
    name: "Meat Kabobs",
    image: "../images/kabobs.jpg",
    type: ["Main"],
    ingredients: [
      "1 lb of 1 inch chunk meat",
      "2 yellow zuchinni",
      "3 mulitcolored peppers",
      "1 yellow onion",
    ],
    steps: [
      "Chop all veggies into 1 inch chunks",
      "Add to skewer in rotation of meat and veggie",
    ],
  },
  {
    name: "Pasta",
    image: "../images/lemon_chicken_mushroom.jpg",
    type: ["Pre-requisite"],
    ingredients: ["1 c soft white flour", "2 eggs"],
    steps: [
      "Pour flour on counter and create a well in the center",
      "Add eggs to well and scramble with fork",
      "Slowly add surrounding flour",
      "Knead until smooth - ~5 minutes",
      "Let rest for 1 hr",
      "Boil water half way up pot and add 3 tbsp salt",
    ],
  },
  {
    name: "Lemon Chicken Mushroom",
    image: "../images/lemon_chicken_mushroom.jpg",
    type: ["Main"],
    ingredients: [
      "3 portabello mushrooms",
      "2 chicken breast",
      "2 lemons - 4tbsp juice",
      "1 tbsp oregano",
      "4 garlic cloves",
      "1/2 tsp salt",
    ],
    steps: [
      "Chop chicken into 1/2 inch cubes",
      "Place chicken in a bowl with lemon, oregano, garlic, and salt",
      "Marinade for 20 minutes",
      "Set oven to 350F",
      "In a pan cook chicken until half cooked",
      "Fill mushrooms with chicken",
      "Bake for 20 minutes",
    ],
  },
  {
    name: "Lotion",
    image: "../images/lotion.jpg",
    type: ["Misc"],
    ingredients: [
      "3/4 c shea butter",
      "1/4 c coconut oil",
      "1 tbsp arrowroot powder",
      "5 drops vitamin E",
      "15 drops vanilla essential oil",
      "15 drops grapefruit essential oil",
    ],
    steps: [
      "Create a double boiler with a smaller glass bowl in a bigger glass bowl",
      "Fill bigger bowl with enough hot water to almost cover the smaller bowl",
      "Melt shea butter and coconut oil in smaller bowl",
      "Place smaller bowl in freezer for 20 minutes or until lotion density",
      "Add essential oils and mix with a hand mixer",
      "Add the arrowroot powder a little at a time with hand mixer",
      "Add to a air tight glass jar, cover and let cool",
    ],
  },
  {
    name: "Mac and Cheese(CICD)",
    image: "../images/mac_and_cheese_cicd.jpg",
    type: ["Main", "Holiday_Thanksgiving"],
    ingredients: [
      "16 oz elbows",
      "1 tbsp olive oil",
      "1/2 c butter",
      "1/3 c flour",
      "3 c milk",
      "1 c heavy whipping cream",
      "4 c shredded sharo cheddar smoked",
      "8 oz cream cheese",
      "1/2 c shredded parmesan",
      "1 1/2 c panko crumbs",
    ],
    steps: [
      "Boil elbows and drain",
      "Toss elbows in oil and set aside",
      "In a large pot whisk over heat slowly, butter, flour, milk, cream, cheddar, and cream cheese",
      "Stir in elbows to pot and pour in baking dish",
      "Mix parmesan and panko crumbs and put on top of elbows",
      "Bake at 350F for 25 minutes",
      "Broil for 5 minutes",
    ],
  },
  {
    name: "Shrimp Mofongo 3 Ways",
    image: "../images/mofongo.jpg",
    type: ["Side", "Main", "Pre-requisite"],
    ingredients: [
      "4 platanos",
      "1 lb shrimp",
      "2 garlic bulbs",
      "olive oil",
      "avocado oil",
      "butter",
    ],
    steps: [
      "1/3 garlic in a glass dish in oil, roast in oven at 350F for 20 minutes",
      "1/3 garlic pan roast in butter",
      "1/3 garlic raw",
      "Chop platanos into 1 inch cubes",
      "Deep fry in olive oil until golden brown",
      "Place platanos in a bowl and set aside",
      "Cook shrimp and drain water",
      "Add pan roasted garlic to shrimp",
      "Mash platanos (add avocado oil if too dry)",
      "Add all to bowl",
    ],
  },
  {
    name: "Paella",
    image: "../images/paella.jpg",
    type: ["Main"],
    ingredients: [
      "frozen shrimp",
      "frozen shelled scallops",
      "frozen shelled mussels",
      "2 jalepenos",
      "2 tomatoes",
      "1/2 c white rice",
      "1 tsp onion powder",
      "1 tsp garlic powder",
      "1 tsp oregano",
    ],
    steps: [
      "Add shrimp, scallops, and mussels to a large pot",
      "Once seafood is defrosted add rice, onion powder, garlic powder, oregano, 1/4 c water, 1 chopped tomato, and chopped jalepenos with seeds",
      "Cook for 20 minutes on low heat",
      "Garnish with 1 chopped tomato",
    ],
  },
  {
    name: "Peanut Butter Oats",
    image: "../images/peanut_butter_oats.jpg",
    type: ["Dessert"],
    ingredients: [
      "1 c rolled oats",
      "3/4 c soft white flour",
      "1 1/2 tsp baking powder",
      "1/2 tsp cinnamon",
      "1/8 tsp salt",
      "1 egg white",
      "1 tsp vanilla",
      "1/3 c peanut butter",
      "1/2 c hiney",
      "5 tbsp milk",
    ],
    steps: [
      "Set oven to 300F",
      "In a bowl 1 mix oats, flour, baking powder, cinnamon, and salt",
      "In bowl 2 mix egg and vanilla, stir in peanut butter, stir in honey, stir in milk",
      "Stir in bowl 1 to bowl 2",
      "Place in 8 inch pan and bake for 12 min",
      "Rest for 4 hrs",
    ],
  },
  {
    name: "Pernil",
    image: "../images/pernil.jpg",
    type: ["Main", "Holiday_Christmas"],
    ingredients: [
      "1/4 c olive oil",
      "4 lb pork shoulder",
      "1 tbsp adobo",
      "2 sazon packets",
      "1/2 tbsp black pepper",
      "1/2 tbsp thyme",
      "1 tbsp garlic powder",
      "1 tbsp onion powder",
    ],
    steps: [
      "Mix all spices and oil in a bowl",
      "Stab pork with knife and add mixture all over pork",
      "Let marinade in the fridge skin side down overnight",
      "Take out of fridge 1 hour before cooking",
      "Set oven to 275F and bake pernil skin side down for 2 hrs covered in foil",
      "Remove foil and bake for another 2 hrs at 350F skin side up",
    ],
  },
  {
    name: "Pie Crust",
    image: "../images/pie_crust.jpg",
    type: ["Bakery"],
    ingredients: [
      "2 c soft white flour",
      "1/4 tsp salt",
      "3 tbsp cold butter",
      "1/4 c + 3 tbsp cold coconut oil",
      "1/4 c ice water",
    ],
    steps: [
      "In a the stand mixer bowl whisk flour and salt",
      "Place in fridge for 20 min",
      "Whisk in cubed butter mix for 1 min on lvl 1",
      "Whisk in coconut oil at lvl 4, should look like dry cookie dough",
      "Replace whisk with dough hook and slowly add the ice water until it looks like wet cookie dough",
      "Roll into a ball and place in fridge for 2 hrs",
      "Flour counter, roll out dough, place in pan and leave in fridge for 30 min",
      "Add filling",
      "Place in oven at 425F for 15 min",
      "Lower oven to 350 for 35 min",
    ],
  },
  {
    name: "Pizza Crust(1-10 inch)",
    image: "../images/pizza_crust.jpg",
    type: ["Bakery"],
    ingredients: [
      "2/3 c warm water",
      "1/4 tsp yeast",
      "1/2 tsp honey",
      "1 1/2 tsp salt",
      "1 1/2 c soft white flour",
      "2 tbsp avocado oil",
      "2 tsp garlic powder",
      "1/2 tsp oregano",
    ],
    steps: [
      "Mix water, yeast, honey, 1 tsp salt and let sit for 5 minutes",
      "Add flour and knead for 2 minutes",
      "Cover and rest for 5 hours",
      "Fold over 8 times and rest or another 2 hours",
      "Roll out pizza",
      "Set oven to 550F and bake for 10 minutes",
      "Mix in a small bowl 1/2 tsp salt, avocado oil, garlic powder, and oregano",
      "Brush on crust",
    ],
  },
  {
    name: "Garlic Tostones",
    image: "../images/garlic_tostones.jpg",
    type: ["Side"],
    ingredients: ["6 platanos", "2 c olive oil", "garlic sauce recipe"],
    steps: [
      "Peel platanos and chop into 1 inch cubes",
      "Heat olive oil in pan",
      "Add platanos flat bottom in pan",
      "Fry for 3 minutes each side",
      "Remove platanos from oil and place them on paper towel to cool",
      "Make garlic sauce recipe",
      "Reheat pan",
      "Flatten platanos and add to oil",
      "Fry for 2 minutes each side",
    ],
  },
  {
    name: "Garlic Sauce",
    image: "../images/garlic_sauce.jpg",
    type: ["Sauce"],
    ingredients: ["2 garlic bulbs", "1/3 c avocado oil", "salt", "pepper"],
    steps: ["Peel and chop garlic", "Add all to a small bowl"],
  },
  {
    name: "Pollo Guisado",
    image: "../images/pollo_guisado.jpg",
    type: ["Main"],
    ingredients: [
      "4 chicken thighs",
      "6 drumsticks",
      "4 brown potatoes",
      "6 carrots",
      "3/4 c sofrito",
      "3/4 c tomato paste",
      "Veggie broth recipe",
      "1/4 c olive oil",
      "2 tbsp salt",
    ],
    steps: [
      "Make veggie broth recipe",
      "Chop chicken and put in pot",
      "Add broth, oil, sofrito, salsa",
      "Bring to boil",
      "Add 1 inch chopped potatoes, salt, and carrots",
      "Bring to boil and remove after 20 minutes",
    ],
  },
  {
    name: "Sofrito",
    image: "../images/pollo_guisado.jpg",
    type: ["Sauce"],
    ingredients: [],
    steps: [],
  },
  {
    name: "Rostiaire Chicken",
    image: "../images/rostiaire_chicken.jpg",
    type: ["Main"],
    ingredients: [
      "~5 lb whole chicken",
      "baking string",
      "1 tsp thyme",
      "1/4 c olive oil",
      "1 tsp paprika",
      "1 tsp oregano",
      "1 tsp onion powder",
      "2 tsp garlic powder",
      "1 packet sazon",
      "1 tsp adobo",
      "rostiaire machine",
    ],
    steps: [
      "Mix all spices and oil in a bowl",
      "Put mixture under skin of chicken",
      "Use the baking string to tie the legs, arms, and around whole chicken",
      "Marinade for 1 hr and remove from fridge 1 hour before baking",
      "Place in machine and airfry for 15 minutes/lb",
      "* Chicken temp: 165F",
    ],
  },
  {
    name: "Salmon",
    image: "../images/salmon.jpg",
    type: ["Main"],
    ingredients: ["salmon", "butter", "salt", "basil", "onion powder"],
    steps: [
      "Set oven to 400F",
      "Add to salmon, salt, onion, basil, and butter",
      "Bake for 10 minutes",
      "* Salmon temp: 145F",
    ],
  },
  {
    name: "Sausage Boats",
    image: "../images/sausage_boats.jpg",
    type: ["Main"],
    ingredients: [
      "1/2 bread recipe ingredients",
      "8 olives",
      "1 tomato",
      "1 cucumber",
      "1/4 cup choppped red onion",
      "1 lb sausage",
      "mayo",
      "ketchup",
      "spicy mustard",
    ],
    steps: [
      "Make bread recipe and split the dough in half",
      "create an aluminum wall high enough to seperate the 2 halfs",
      "Add parchment paper to each half",
      "Bake at 350 for 25 minutes",
      "Create hotdog shapes with sausage and cook",
      "Let bread cool while cooking sausage",
      "Chop all veggies",
      "Scoop out insides of bread",
    ],
  },
  {
    name: "Shawns Chili",
    image: "../images/shawns_chili.jpg",
    type: ["Main"],
    ingredients: [
      "2 lbs ground beef",
      "6 tomatoes chopped",
      "16 oz red kidney beans(black beans recipe)",
      "2 corn",
      "2 garlic bulbs",
      "shredded cheese",
      "1 onion",
      "3 peppers",
      "2 jalapenos plus seeds",
      "2 tbsp salt",
    ],
    steps: [
      "Chop all veggies",
      "Add to large pot",
      "Add beans and bean water to pot",
      "Cook on low",
    ],
  },
  {
    name: "Shawns Lemonade",
    image: "../images/shawns_lemonade.jpg",
    type: ["Drink"],
    ingredients: ["1 cup water", "2 tbsp agave", "3 tbsp lemon juice", "ice"],
    steps: ["Stir water, agave, and lemon juice in a cup", "Fill cup with ice"],
  },
  {
    name: "Shawns Tea(2)",
    image: "../images/shawns_tea.jpg",
    type: ["Drink"],
    ingredients: [
      "4 tbsp black tea",
      "2 lemons",
      "6 tbsp agave",
      "ice",
      "3 cups boiling water",
    ],
    steps: [
      "Seep tea for 5 minutes in water",
      "Pour 1 cup of tea in glass",
      "Stir in 3 tbsp of agave one at a time",
      "Stir in 2 tbsp of lemon juice",
      "Add ice up to 1 inch below rim of glass",
      "Add 1/2 c tea and stir",
      "Add 1 tbsp lemon juice and stir",
    ],
  },
  {
    name: "Shepherds Pie",
    image: "../images/shepherds_pie.jpg",
    type: ["Main"],
    ingredients: [
      "2 lbs ground beef",
      "3 brown potatoes",
      "1 carrot stick",
      "1/2 yellow onion",
      "1/2 green pepper",
      "1 packet sazon",
      "1/2 tbsp adobo",
    ],
    steps: [
      "Set oven to 350F",
      "Boil 1/2 large pot with water",
      "Chop potatoes into 1 inch cubes and add to boiling water",
      "Boil for 20 minutes",
      "Cook ground beef, drain, set aside",
      "Chop carrot into coins and cook in pot that held the ground beef",
      "Once carrots are a little charred add onion and green pepper",
      "Once veggies look soft add the sazon, adobo, and ground beef",
      "Add to glass dish and flatten",
      "Mash potatoes and flatten on top of beef",
      "Bake for 30 minutes",
    ],
  },
  {
    name: "Shoulder Roast",
    image: "../images/shoulder_roast.jpg",
    type: ["Main"],
    ingredients: [
      "bone broth recipe",
      "2 tbsp onion powder",
      "1 tbsp salt",
      "1/2 tbsp thyme",
      "1/2 tbsp smoked paprika",
      "4 lb shoulder roast",
    ],
    steps: [
      "Make bone broth recipe",
      "Add all spices to pot",
      "Stab roast with fork and add to pot",
      "Bake for 30 minutes, flip roast, and finish baking for 30 miutes",
      "* Roast temp: 145F",
    ],
  },
  {
    name: "Spaghetti Squash and Meatballs",
    image: "../images/spaghetti_and_meatballs.jpg",
    type: ["Main", "Pre-requisite"],
    ingredients: ["Spaghetti squash", "Meatball recipe", "Tomato Sauce recipe"],
    steps: [
      "Make meatball recipe",
      "Make tomato sauce recipe",
      "Set oven to 400F",
      "Cut spaghetti squash in half the long way",
      "Scoop out the seeds and drizzle olive oil",
      "Add salt and pepper",
      "Place shell side up on baking pan",
      "Bake for 30 minutes",
      "Once cooled, shred with fork",
    ],
  },
  {
    name: "Spaghetti and Meatballs",
    image: "../images/spaghetti_and_meatballs.jpg",
    type: ["Main", "Pre-requisite"],
    ingredients: ["Spaghetti recipe", "Meatball recips", "Tomato Sauce recipe"],
    steps: [
      "Make spaghetti recipe",
      "Make tomato sauce recipe",
      "Make meatball recipe and add to sauce",
    ],
  },
  {
    name: "Meatballs",
    image: "../images/spaghetti_and_meatballs.jpg",
    type: ["Pre-requisite"],
    ingredients: [
      "1 lb ground beef",
      "1 tsp chili pepper flakes",
      "1 tsp garlic powder",
      "1 tsp onion powder",
      "1/2 tsp basil",
      "1/2 tsp parsley",
      "1 tbsp salt",
    ],
    steps: [
      "Mix all in a pot by hand",
      "Create 1 inch balls",
      "Sear all sides in a large pan",
      "* Meatball temp: 145F",
    ],
  },
  {
    name: "Spaghetti",
    image: "../images/spaghetti.jpg",
    type: ["Pre-requisite"],
    ingredients: ["Pasta recipe", "1 1/2 tbsp salt", "1 tbsp olive oil"],
    steps: [
      "Make pasta recipe",
      "Fill large pot half way with water to boil",
      "Cut pasta into 8 pieces",
      "Roll out each piece and flatten with pasta machine",
      "Pass through spaghetti part of machine",
      "Once water is boiling add salt and pasta",
      "Boil for 3 minutes",
      "Drain water and add olive oil",
    ],
  },
  {
    name: "Spanish Rice",
    image: "../images/spanish_rice.jpg",
    type: ["Side"],
    ingredients: [
      "black beans recipe",
      "1 c white rice",
      "1 tbsp coconut oil",
      "1 packet sazon",
      "2 tsp adobo",
      "1 can tomato sauce",
      "1 1/4 c water",
      "1 tbsp sofrito",
    ],
    steps: [
      "Make balck beans",
      "Add all to pot and bring to boil",
      "Simmer for 40 minutes",
    ],
  },
  {
    name: "Black Beans",
    image: "../images/black_beans.jpg",
    type: ["Side"],
    ingredients: ["1 1/2 c water", "1/2 c black beans", "1 tsp salt"],
    steps: ["Add all to pot and bring to boil", "Simmer for 2 hrs"],
  },
  {
    name: "White Rice",
    image: "../images/white_rice.jpg",
    type: ["Side"],
    ingredients: [
      "1 c white rice",
      "2 tsp salt",
      "1 tbsp coconut oil",
      "1 1/2 c water",
    ],
    steps: [
      "Add water, salt, oil, and rice to pot",
      "Bring to boil then simmer for 25 minutes",
    ],
  },
  {
    name: "Steak",
    image: "../images/steak_potato.jpg",
    type: ["Main"],
    ingredients: ["1 lb steak", "Salt"],
    steps: [
      "Set oven to 450F",
      "Add a good layer of salt all over steak",
      "Cook steak on cast iron skillet on stove top for 3 minutes",
      "Flip steak and bake for 4 minutes",
    ],
  },
  {
    name: "Stove Cleaner",
    image: "../images/stove_cleaner.jpg",
    type: ["Misc"],
    ingredients: ["1 c baking soda", "1/4 c lquid soap", "hydrogen peroxide"],
    steps: [
      "Mix all into a paste",
      "Scrub onto stove",
      "Let sit for 30 minutes",
    ],
  },
  {
    name: "Strawberry Jam",
    image: "../images/strawberry_jam.jpg",
    type: ["Jam"],
    ingredients: [
      "1 lb strawberries",
      "5 tbsp lemon juice",
      "2/3 c agave",
      "1 mason jar for storage",
    ],
    steps: [
      "Blend strawberries",
      "Set oven to 200F",
      "Add strawberries, lemon, and agave to a pot on medium heat",
      "Turn off stove and place jar in oven for 20 mimutes",
      "Boil strawberries while stirring every 10 minutes until thickened about 30 minutes",
      "Place in jar, seal, and let cool",
    ],
  },
  {
    name: "Stuffed Cabbage",
    image: "../images/stuffed_cabbage.jpg",
    type: ["Main"],
    ingredients: [
      "1 cabbage",
      "1 yellow onion",
      "cilantro",
      "2 tomatoes",
      "1/2 white rice recipe",
      "tomato paste",
      "1 lb ground beef",
      "1 tsp garlic powder",
      "1 tsp oregano",
      "1 tsp red chili flakes",
      "1 tbsp salt",
      "1 tsp pepper",
      "1 tsp smoked paprika",
    ],
    steps: [
      "Make white rice recipe",
      "Boil water in a large pot",
      "Add whole cabbage to pot and boil for 20 minutes",
      "Set oven to 375F",
      "In a large bowl add onion, cilantro, rice, ground beef, garlic powder, oregano, chili flakes, salt, pepper, and smoked paprika and combine with hands",
      "Remove cabbage from boiling water and place in a bolw of ice water",
      "Peel one leaf of cabbage at a time and fill with ground beef",
      "Continue to roll up into a small egg roll shape and place in glass dish",
      "In blender add tomatoes and tomato paste",
      "Pour tomato sauce over cabbge rolls",
      "Bake for 30 minutes",
      "* Cabbage temp: 145F",
    ],
  },
  {
    name: "Stuffed Chicken",
    image: "../images/stuffed_chicken.jpg",
    type: ["Main"],
    ingredients: [
      "2 chicken breast",
      "1 tomato",
      "1 bunch of spinach",
      "1 bulb of garlic",
      "1 shallot",
      "1 tsp salt",
      "1 tsp onion powder",
      "1 tsp garlic powder",
      "1 tbsp avocado oil",
    ],
    steps: [
      "set oven to 450F",
      "Cut chicken breast in half the long way but not all the way through",
      "Set aside chopped garlic, sliced shallot, and sliced tomato",
      "Add 1/2 tsp salt, 1/2 tsp onion powder, and 1/2 tsp garlic powder to inside of chicken",
      "In pan add olive oil and garlic",
      "Once garlic has started to turn golden brown add spinach",
      "Once spinach has whithered set aside",
      "Layer 1/2 spinash, 1/2 shallots, and 1/2 tomatoes inside chicken",
      "Close chicken, use toothpicks if it does not stay closed",
      "Add left over salt, onion powder, garlic powder, spinash, shallot, and toamto to top of chicken",
      "Bake for 45 minutes",
      "* Chicken temp: 165F",
    ],
  },
  {
    name: "Sushi",
    image: "../images/sushi.jpg",
    type: ["Main"],
    ingredients: [
      "seaweed",
      "white rice recipe",
      "shrimp",
      "1 cucumber",
      "1 avocado",
    ],
    steps: [
      "Make white rice recipe",
      "Cook shrimp",
      "Chop shrimp, cucumber, and avocado into thin strips",
      "Lay seaweed and add a thin layer of rice",
      "Add shrimp, cucumber, and avocado in a line on top of rice",
      "Roll seaweed tightly and slice into 1 inch pieces",
    ],
  },
  {
    name: "Sweet Potato Casserole",
    image: "../images/sweet_potato_casserole.jpg",
    type: ["Holiday_Thanksgiving"],
    ingredients: [
      "5 sweet potatoes",
      "1/2 c brown sugar",
      "1/4 c butter",
      "3 tbsp orange juice",
      "1 tsp groud cinnamon",
      "1 10.5 oz mini marshmallows",
    ],
    steps: [
      "Boil sweet potatoes and mash in mixing bowl",
      "Stir in brown sugar, butter, orange juice, and cinnamon to bowl",
      "Add marshmallows on top and bake at 350F for 30 minutes",
    ],
  },
  {
    name: "Tomato Sauce",
    image: "../images/tomato_sauce.jpg",
    type: ["Sauce"],
    ingredients: [
      "8 tomatoes",
      "1 tbsp garlic powder",
      "1 tbsp onion powder",
      "1/2 tbsp honey",
      "1 tsp chili flakes",
      "1/2 tbsp oregano",
    ],
    steps: [
      "Remove core from tomatoes and blend",
      "Add all ingredients to pot and bring to boil",
      "Simmer for 30 minutes",
    ],
  },
  {
    name: "Top Round Steak",
    image: "../images/top_round.jpg",
    type: ["Main"],
    ingredients: ["1 lb top round steak", "salt", "olive oil"],
    steps: [
      "Smash steak to soften meat",
      "Add salt and oil and marindae for 2 hours",
      "Put steak in broil safe cooking sheet",
      "Broild each side for 3 minutes",
    ],
  },
  {
    name: "Tortilla Chips",
    image: "../images/tortilla_chips.jpg",
    type: ["Side", "Pre-requisite"],
    ingredients: ["Left over masa", "olive oil", "salt"],
    steps: [
      "Set oven to 350F",
      "Slice masa into trinagles and put on pan",
      "Brush oliv oil on slices and add salt",
      "Bake for 5 minutes",
    ],
  },
  {
    name: "Waffles(2)",
    image: "../images/waffles_pancakes.jpg",
    type: ["Breakfast"],
    ingredients: [
      "1 c red flour",
      "1 tbsp honey",
      "1/2 tbsp baking powder",
      "1 tsp salt",
      "3/4 c milk",
      "1 egg",
      "1/8 c olive oil",
      "1 tsp vanilla",
    ],
    steps: ["Mix all in a bowl", "Rest for 5 minutes"],
  },
  {
    name: "Pancakes(10)",
    image: "../images/waffles_pancakes.jpg",
    type: ["Breakfast"],
    ingredients: [
      "1 c red flour",
      "1 tbsp honey",
      "1/2 tbsp baking powder",
      "1 tsp salt",
      "3/4 c milk",
      "1 egg",
      "1/8 c olive oil",
      "1 tsp vanilla",
    ],
    steps: ["Mix all in a bowl", "Rest for 5 minutes"],
  },
  {
    name: "Zuchini Bread",
    image: "../images/zuchini_bread.jpg",
    type: ["Dessert"],
    ingredients: [
      "1 3/4 c hard red flour",
      "1/2 tsp salt",
      "1/2 tsp baking soda",
      "1/2 tsp baking powder",
      "2 tsp cinnamon",
      "1 3/4 c shredded zuchini",
      "2 eggs",
      "1/4 c apple sauce",
      "1/4 c olive oil",
      "1/2 c honey",
      "1/3 c agave",
      "2 tsp vanilla",
    ],
    steps: ["Set oven to 375F", "Mix all ingrdients and bake for 1 hr"],
  },
  {
    name: "Taco Dip",
    image: "Errr...loading...taco_dip",
    type: ["Main"],
    ingredients: [
      "1 lb ground beef",
      "2 tsp salt",
      "8 oz cream cheese",
      "shredded lettuce",
      "2 tomatoes",
      "1 can refried black beans",
      "8 oz shredded cheese",
    ],
    steps: [
      "Fully cook ground beef with salt",
      "Drain ground beef and place in 8 inch glass dish",
      "Add a layer of refried beans",
      "Add layer of room temp cream cheese",
      "Add chopped tomatoes, lettuce, and shredded cheese",
    ],
  },
  {
    name: "Chicken Parm",
    image: "no image found",
    type: ["Main"],
    ingredients: [
      "1 c hard white flour",
      "4 1/2 tbsp salt",
      "2 tbsp italian seasoning",
      "1 egg",
      "1/6 c milk",
      "Olive oil",
      "3 chicken breast",
      "Mozerella cheese",
      "Parmesan cheese",
      "Pasta recipe",
      "Marinara sauce recipe",
    ],
    steps: [
      "Make marinara sauce recipe",
      "Make pasta recipe",
      "In a bowl mix hard white flour, 1 1/2 tbsp salt, 1/4 c shredded parmesan, and italian seasoning",
      "In a separate bowl mix egg and milk",
      "In a flat bottom pan add enough olive oil so chicken is half submerged",
      "Set oven to 450F",
      "Cut chicken breast in half and dip in egg , flour, egg, then flour again",
      "Fry each side of the chicken for 3 minutes",
      "In a glass dish add chicken and 2 slices of mozerella cheese",
      "Bake for 10 minutes",
    ],
  },
  {
    name: "Marinara Sauce",
    image: "no image found",
    type: ["Sauce"],
    ingredients: [
      "6 whole peeled tomatoes",
      "1/2 c olive oil",
      "1 yellow onion",
      "1/2 tbsp salt",
      "1 garlic bulb",
      "1/2 tbsp oregano",
      "1/2 tbsp basil",
      "1 tsp black pepper",
    ],
    steps: [
      "Blend all",
      "Add to a pot and bring to boil",
      "Simmer for 30 minutes",
      "Store in mason jar",
    ],
  },
  // {
  //   name: ,
  //   image: ,
  //   type: ["Main", "Holiday_Thanksgiving", "Holiday_Christmas", "Dessert", "Bakery", "Misc", "Drink", "Side", "Pre-requisite", "Sauce", "Jam"],
  //   ingredients: [
  //   ],
  //   steps: [
  //   ],
  // },
]
